import type { Category, Product } from '@/types'

const now = new Date().toISOString()

export const STATIC_CATEGORIES: Category[] = [
  { id: 'cat-01', name: 'Sites Web', slug: 'sites-web', description: 'Sites vitrine, corporate, institutionnels — design moderne, mobile-first et optimisés Google.', sort_order: 1, is_active: true },
  { id: 'cat-02', name: 'E-commerce', slug: 'ecommerce', description: 'Boutiques en ligne clé en main avec intégration paiement Mobile Money, livraison et gestion stock.', sort_order: 2, is_active: true },
  { id: 'cat-03', name: 'Applications', slug: 'applications', description: 'Applications web, mobiles iOS/Android et PWA sur mesure pour votre business.', sort_order: 3, is_active: true },
  { id: 'cat-04', name: 'Documents QR', slug: 'documents-qr', description: 'Menus, catalogues, CV, cartes de visite et brochures digitales accessibles par QR code.', sort_order: 4, is_active: true },
  { id: 'cat-05', name: 'Design & Branding', slug: 'design', description: 'Identité visuelle, logo, charte graphique et tous vos supports de communication.', sort_order: 5, is_active: true },
  { id: 'cat-06', name: 'Marketing Digital', slug: 'marketing-digital', description: 'Stratégie digitale, publicité Facebook/Google, gestion de campagnes et acquisition de clients.', sort_order: 6, is_active: true },
  { id: 'cat-07', name: 'IA & Automatisation', slug: 'ia-automatisation', description: 'Chatbots, agents IA, automatisation des processus et intégrations intelligentes.', sort_order: 7, is_active: true },
  { id: 'cat-08', name: 'Community Management', slug: 'community-management', description: 'Gestion complète de vos réseaux sociaux, création de contenu et animation de communauté.', sort_order: 8, is_active: true },
  { id: 'cat-09', name: 'SEO & Référencement', slug: 'seo', description: 'Audit, optimisation et positionnement Google pour attirer un trafic qualifié et durable.', sort_order: 9, is_active: true },
  { id: 'cat-10', name: 'Hébergement & Cloud', slug: 'hebergement', description: 'Hébergement professionnel, nom de domaine, SSL, sauvegardes et infogérance.', sort_order: 10, is_active: true },
  { id: 'cat-11', name: 'Cybersécurité', slug: 'cybersecurite', description: 'Audit de sécurité, protection de site, antivirus, pare-feu et conformité RGPD.', sort_order: 11, is_active: true },
  { id: 'cat-12', name: 'Formation Digitale', slug: 'formation', description: 'Formations pratiques aux outils digitaux, marketing et technologies pour vos équipes.', sort_order: 12, is_active: true },
  { id: 'cat-13', name: 'Vidéo & Contenu', slug: 'video-contenu', description: 'Production vidéo, motion design, photos professionnelles et création de contenu multimédia.', sort_order: 13, is_active: true },
  { id: 'cat-14', name: 'Emailing & CRM', slug: 'emailing', description: 'Campagnes emailing, newsletters, automatisation marketing et gestion de la relation client.', sort_order: 14, is_active: true },
  { id: 'cat-15', name: 'Consulting Digital', slug: 'consulting-digital', description: 'Audit digital, stratégie de transformation numérique et accompagnement sur mesure.', sort_order: 15, is_active: true },
  { id: 'cat-16', name: 'Print & Supports', slug: 'print-supports', description: 'Conception et impression de supports physiques : flyers, roll-up, kakémono, brochures.', sort_order: 16, is_active: true },
  { id: 'cat-17', name: 'Cartes Digitales', slug: 'cartes-digitales', description: 'Cartes de visite digitales NFC et QR, vCards professionnelles et profils interactifs.', sort_order: 17, is_active: true },
  { id: 'cat-18', name: 'WhatsApp Business', slug: 'whatsapp-business', description: 'Configuration, automatisation et stratégie WhatsApp Business pour votre relation client.', sort_order: 18, is_active: true },
]

function cat(id: string) {
  return STATIC_CATEGORIES.find(c => c.id === id)!
}

function p(
  id: string, catId: string, name: string, slug: string,
  price: number | undefined, price_type: 'fixed'|'from'|'on_quote',
  short_description: string, delivery: string, featured = false,
  features: string[] = []
): Product {
  return {
    id, category_id: catId, name, slug, price, price_type,
    currency: 'XOF', short_description,
    delivery_time: delivery,
    is_featured: featured, is_active: true,
    is_partner_visible: true, is_affiliate_enabled: true,
    sort_order: 0, created_at: now, updated_at: now,
    category: cat(catId), features,
  }
}

export const STATIC_PRODUCTS: Product[] = [

  /* ══════════ SITES WEB ══════════ */
  p('sw-01','cat-01','Site Vitrine Essentiel','site-vitrine-essentiel',120000,'fixed',
    'Site web 5 pages, design moderne, mobile-first, formulaire de contact et intégration réseaux sociaux.','2–3 semaines',true,
    ['5 pages (Accueil, Services, À propos, Contact, Galerie)','Design responsive mobile-first','Formulaire de contact','Intégration réseaux sociaux','Optimisation SEO de base','Livraison clé en main']),
  p('sw-02','cat-01','Site Corporate Premium','site-corporate-premium',350000,'from',
    'Site institutionnel multi-pages avec espace blog, témoignages, multilingue et dashboard admin.','4–6 semaines',true,
    ['10–20 pages personnalisées','Blog intégré','Espace multilingue (FR/EN)','Dashboard d\'administration','Animations et transitions premium','SEO avancé + Google Analytics']),
  p('sw-03','cat-01','Site Portfolio / Créatif','site-portfolio-creatif',150000,'from',
    'Portfolio interactif pour freelances, agences, artistes et créatifs. Galerie dynamique, animations.','2–4 semaines',false,
    ['Galerie projets dynamique','Filtres par catégorie','Formulaire de contact intégré','Design minimaliste et impactant','Compatible iPad/mobile']),
  p('sw-04','cat-01','Landing Page Conversion','landing-page-conversion',75000,'fixed',
    'Page de vente ou de capture ultra-optimisée pour convertir vos visiteurs en clients ou prospects.','1 semaine',false,
    ['1 page ultra-optimisée','Boutons CTA stratégiques','Témoignages intégrés','Formulaire de capture','Vitesse de chargement < 2s','A/B testing possible']),
  p('sw-05','cat-01','Refonte de Site Web','refonte-site-web',200000,'from',
    'Modernisation complète de votre site existant : nouveau design, meilleure expérience utilisateur, SEO.','3–5 semaines',false,
    ['Audit de l\'existant','Nouveau design premium','Migration du contenu','Optimisation vitesse','SEO on-page complet','Redirection 301']),
  p('sw-06','cat-01','Site Association / ONG','site-association-ong',100000,'from',
    'Site web dédié aux associations et ONG avec gestion des membres, événements et donations.','2–4 semaines',false,
    ['Gestion des membres','Agenda événements','Module dons/adhésion','Galerie photos','Newsletter intégrée','Administration simplifiée']),
  p('sw-07','cat-01','Site Restaurant / Hôtel','site-restaurant-hotel',180000,'from',
    'Site spécialisé pour restaurants, hôtels et établissements avec menu digital, réservation en ligne.','2–4 semaines',false,
    ['Menu digital interactif','Réservation en ligne','Galerie plats/chambres','Intégration Google Maps','Avis clients','Multi-langues']),

  /* ══════════ E-COMMERCE ══════════ */
  p('ec-01','cat-02','Boutique en Ligne Starter','boutique-en-ligne-starter',250000,'fixed',
    'Boutique e-commerce complète jusqu\'à 50 produits, paiement Mobile Money, gestion commandes.','3–5 semaines',true,
    ['Jusqu\'à 50 produits','Paiement Orange Money, MTN, Wave','Gestion commandes','Panel d\'administration','Livraison configurable','Fiches produits optimisées']),
  p('ec-02','cat-02','Boutique E-commerce Pro','boutique-ecommerce-pro',500000,'from',
    'Plateforme e-commerce avancée : produits illimités, multi-vendeurs, promotions, analytics.','5–8 semaines',true,
    ['Produits illimités','Gestion multi-vendeurs','Codes promotionnels','Système de fidélité','Analytics avancés','API Mobile Money']),
  p('ec-03','cat-02','Marketplace Africaine','marketplace-africaine',1500000,'from',
    'Plateforme marketplace multi-vendeurs type Jumia/Amazon adaptée au marché africain.','8–16 semaines',false,
    ['Multi-vendeurs illimités','Tableau de bord vendeurs','Commissions automatisées','Gestion litiges','Mobile Money multi-opérateurs','Panel super-admin']),
  p('ec-04','cat-02','Intégration Mobile Money','integration-mobile-money',80000,'fixed',
    'Intégration des paiements Mobile Money (Orange, MTN, Wave, Moov) sur votre site existant.','1–2 semaines',false,
    ['Orange Money CI','MTN MoMo','Wave','Moov Money','Rapprochement automatique','Dashboard paiements']),
  p('ec-05','cat-02','Gestion Catalogue Produits','gestion-catalogue-produits',50000,'fixed',
    'Saisie, organisation et optimisation de votre catalogue produits : photos, descriptions, SEO.','1–2 semaines',false,
    ['Saisie produits','Photos retouchées','Descriptions optimisées','Catégorisation','Import CSV','Prix et stocks']),
  p('ec-06','cat-02','Click & Collect','click-and-collect',120000,'fixed',
    'Système de commande en ligne avec retrait en magasin. Idéal pour les commerces physiques.','2–3 semaines',false,
    ['Commande en ligne','Créneaux de retrait','Notifications SMS/email','Gestion stock','QR code de retrait','Dashboard caissier']),

  /* ══════════ APPLICATIONS ══════════ */
  p('ap-01','cat-03','Application Web Sur Mesure','application-web-sur-mesure',undefined,'on_quote',
    'Application web métier entièrement personnalisée : CRM, ERP, gestion de stock, RH, logistique.','8–20 semaines',true,
    ['Analyse des besoins','Architecture sur mesure','Interface admin','API REST','Authentification sécurisée','Documentation technique']),
  p('ap-02','cat-03','Application Mobile iOS/Android','application-mobile-ios-android',undefined,'on_quote',
    'Application mobile native ou cross-platform (React Native, Flutter) pour iOS et Android.','10–24 semaines',true,
    ['iOS + Android','Design UI/UX natif','Notifications push','Mode offline','Publication App Store / Play Store','Support technique']),
  p('ap-03','cat-03','Progressive Web App (PWA)','progressive-web-app',350000,'from',
    'Application installable depuis le navigateur, fonctionne offline, performances natives.','4–8 semaines',false,
    ['Installable sur mobile','Mode offline','Notifications push','Performances natives','Compatible tous OS','Coût < app native']),
  p('ap-04','cat-03','Application Livraison','application-livraison',undefined,'on_quote',
    'Plateforme complète de livraison à domicile : app client, app livreur, dashboard dispatch.','12–20 semaines',false,
    ['App client (commande)','App livreur (géolocalisation)','Dashboard dispatch','Suivi temps réel','Paiement intégré','Historique et analytics']),
  p('ap-05','cat-03','Système de Réservation','systeme-reservation',200000,'from',
    'Plateforme de réservation en ligne : restaurants, salons, cliniques, hôtels, prestataires.','3–6 semaines',false,
    ['Calendrier disponibilités','Réservation en ligne 24h/24','Rappels automatiques SMS/email','Paiement optionnel','Dashboard gestion','Multi-services']),
  p('ap-06','cat-03','Tableau de Bord Analytics','tableau-de-bord-analytics',150000,'from',
    'Dashboard personnalisé avec vos KPIs business : ventes, clients, performance, rapports.','2–5 semaines',false,
    ['KPIs personnalisés','Graphiques interactifs','Rapports automatiques','Export PDF/Excel','Alertes par email','Multi-utilisateurs']),

  /* ══════════ DOCUMENTS QR ══════════ */
  p('qr-01','cat-04','Menu Digital Restaurant','menu-digital-restaurant',45000,'fixed',
    'Menu interactif accessible par QR code : catégories, photos, prix, allergènes. Mise à jour en temps réel.','3–5 jours',true,
    ['QR code personnalisé','Catégories et sous-catégories','Photos des plats','Prix et allergènes','Mise à jour instantanée','Compatible tous smartphones']),
  p('qr-02','cat-04','Carte de Visite QR','carte-de-visite-qr',25000,'fixed',
    'Carte de visite digitale avec QR code redirigeant vers votre profil complet, contacts et réseaux.','2–3 jours',false,
    ['QR code unique','Profil professionnel complet','Lien vers réseaux sociaux','Bouton d\'appel direct','Partage WhatsApp','Mise à jour sans reimpression']),
  p('qr-03','cat-04','Catalogue Digital','catalogue-digital-qr',80000,'from',
    'Catalogue produits ou services interactif avec QR code : photos HD, descriptions, tarifs.','1–2 semaines',false,
    ['Catalogue illimité','Photos haute définition','Filtres et recherche','Formulaire de commande','Analytics visiteurs','Mise à jour facile']),
  p('qr-04','cat-04','CV Interactif QR','cv-interactif-qr',30000,'fixed',
    'CV digital premium avec QR code pour vos candidatures : portfolio, expériences, compétences.','2–4 jours',false,
    ['QR code sur votre CV papier','Page profil complète','Portfolio intégré','Vidéo de présentation','Téléchargement PDF','Analytics clics']),
  p('qr-05','cat-04','Brochure Digitale','brochure-digitale',60000,'from',
    'Brochure d\'entreprise interactive accessible par QR : texte, images, vidéos, formulaire contact.','1 semaine',false,
    ['Design fidèle à votre charte','Vidéos intégrables','Formulaire de contact','Partage WhatsApp/email','Analytics','Hébergement inclus 1 an']),
  p('qr-06','cat-04','Événement QR','evenement-qr',40000,'fixed',
    'Page événement accessible par QR : programme, invités, RSVP, localisation et galerie photos.','3–5 jours',false,
    ['Programme détaillé','Formulaire RSVP','Localisation Google Maps','Galerie photos post-événement','Compte à rebours','Partage réseaux']),

  /* ══════════ DESIGN & BRANDING ══════════ */
  p('de-01','cat-05','Création de Logo','creation-logo',75000,'from',
    'Conception de logo professionnel avec 3 propositions créatives, retouches illimitées, tous formats.','5–7 jours',true,
    ['3 concepts créatifs','Révisions illimitées','Formats PNG, SVG, PDF','Déclinaisons (noir/blanc, couleur)','Guide utilisation','Fichiers sources']),
  p('de-02','cat-05','Charte Graphique Complète','charte-graphique-complete',180000,'from',
    'Identité visuelle complète : logo, couleurs, typographies, icônes, règles d\'usage et mockups.','2–3 semaines',true,
    ['Logo (primaire + variantes)','Palette de couleurs','Typographies principales','Icônes personnalisées','Guide de style PDF','Mockups réalistes']),
  p('de-03','cat-05','Flyer & Affiche Événement','flyer-affiche-evenement',25000,'fixed',
    'Création de flyers, affiches et visuels pour vos événements, promotions et campagnes.','2–3 jours',false,
    ['Design sur mesure','Format A5/A4/A3','Version print HD','Version réseaux sociaux','Retouches incluses','Fichiers livrables']),
  p('de-04','cat-05','Kit Réseaux Sociaux','kit-reseaux-sociaux',60000,'fixed',
    'Pack de visuels cohérents pour tous vos réseaux : bannières, templates posts, highlights Instagram.','4–6 jours',false,
    ['Photo de profil et couverture','10 templates posts','5 templates Stories','Highlights Instagram','Bannière LinkedIn/Facebook','Format éditable Canva']),
  p('de-05','cat-05','Packaging & Étiquettes','packaging-etiquettes',90000,'from',
    'Design de packaging produit, étiquettes, boîtes et emballages adaptés à votre marque.','1–2 semaines',false,
    ['Design packaging complet','Étiquettes produits','Maquette 3D visuelle','Fichiers prêts à imprimer','Cohérence avec la charte','Plusieurs variantes']),
  p('de-06','cat-05','Présentation PowerPoint Pro','presentation-powerpoint-pro',50000,'from',
    'Template PowerPoint ou Google Slides professionnel aux couleurs de votre entreprise.','3–5 jours',false,
    ['Template aux couleurs de votre marque','20–40 slides modèles','Graphiques et icônes','Animations incluses','Compatible PowerPoint et Keynote','Formation utilisation']),
  p('de-07','cat-05','Identité Visuelle Startup','identite-visuelle-startup',250000,'fixed',
    'Pack complet pour les startups : logo, charte, pitch deck, site landing page et réseaux sociaux.','3–4 semaines',false,
    ['Logo + charte complète','Pitch deck 15 slides','Landing page 1 page','Kit réseaux sociaux','Cartes de visite','Guide de marque']),

  /* ══════════ MARKETING DIGITAL ══════════ */
  p('mk-01','cat-06','Gestion Publicité Facebook/Instagram','gestion-publicite-facebook',150000,'from',
    'Création, gestion et optimisation de vos campagnes publicitaires Facebook et Instagram Ads.','Mensuel',true,
    ['Stratégie de ciblage','Création des visuels','Textes publicitaires','Tests A/B','Optimisation continue','Rapport mensuel']),
  p('mk-02','cat-06','Publicité Google Ads','publicite-google-ads',200000,'from',
    'Campagnes Google Ads (Search, Display, Shopping) pour apparaître en premier sur Google.','Mensuel',false,
    ['Recherche de mots-clés','Création des annonces','Enchères optimisées','Remarketing','Suivi conversions','Rapport mensuel']),
  p('mk-03','cat-06','Stratégie Marketing Digital','strategie-marketing-digital',300000,'from',
    'Audit et élaboration de votre stratégie digitale complète : canaux, budget, KPIs, planning.','2–3 semaines',false,
    ['Audit de votre présence actuelle','Analyse concurrentielle','Stratégie multicanale','Budget et ROI prévisionnel','Planning sur 6 mois','Tableau de bord KPIs']),
  p('mk-04','cat-06','WhatsApp Marketing','whatsapp-marketing',80000,'from',
    'Stratégie et exécution de campagnes WhatsApp : listes de diffusion, automation, relances.','Mensuel',false,
    ['Création liste de contacts','Messages personnalisés','Automatisation réponses','Promotions et offres','Relances paniers','Taux d\'ouverture > 90%']),
  p('mk-05','cat-06','Influence Marketing Afrique','influence-marketing-afrique',200000,'from',
    'Campagnes avec des influenceurs africains : identification, négociation, brief, suivi résultats.','2–6 semaines',false,
    ['Sélection d\'influenceurs ciblés','Négociation contrats','Brief créatif','Suivi campagne','Mesure du ROI','Rapport final']),
  p('mk-06','cat-06','Growth Hacking','growth-hacking',250000,'from',
    'Stratégies d\'acquisition rapide et peu coûteuses : viral, référencement, partenariats, automation.','Mensuel',false,
    ['Audit du funnel actuel','Identification des leviers','Tests et itérations','Automation acquisition','Optimisation conversion','Reporting hebdomadaire']),

  /* ══════════ IA & AUTOMATISATION ══════════ */
  p('ia-01','cat-07','Chatbot IA Service Client','chatbot-ia-service-client',200000,'from',
    'Chatbot intelligent sur votre site web ou WhatsApp : répond 24h/24 aux questions fréquentes.','2–4 semaines',true,
    ['Compréhension langage naturel','Base de connaissances personnalisée','Intégration site ou WhatsApp','Escalade vers humain','Formation continue','Dashboard analytics']),
  p('ia-02','cat-07','Automatisation des Processus','automatisation-processus',300000,'from',
    'Identification et automatisation de vos tâches répétitives : relances, rapports, notifications.','2–6 semaines',true,
    ['Audit de vos processus','Identification opportunités','Développement workflows','Tests et validation','Formation équipe','Support 3 mois']),
  p('ia-03','cat-07','Agent IA Personnalisé','agent-ia-personnalise',500000,'from',
    'Agent IA sur mesure qui connaît votre entreprise et répond à vos clients, prospects et équipes.','4–8 semaines',false,
    ['Formation sur vos données','Intégration multi-canal','Mémoire conversationnelle','Escalade intelligente','Analytics comportementaux','Amélioration continue']),
  p('ia-04','cat-07','Génération de Contenu IA','generation-contenu-ia',100000,'from',
    'Mise en place d\'un système de génération automatique de contenu : posts, descriptions, emails.','1–2 semaines',false,
    ['Templates IA personnalisés','Posts réseaux sociaux auto','Descriptions produits','Emails marketing','Rapport de performance','Formation équipe']),
  p('ia-05','cat-07','Intégration API IA','integration-api-ia',150000,'from',
    'Intégration d\'API d\'intelligence artificielle (OpenAI, Claude, Gemini) dans vos outils existants.','2–4 semaines',false,
    ['Analyse de l\'existant','Choix de l\'API adaptée','Développement connecteur','Tests de performance','Documentation','Support 1 mois']),
  p('ia-06','cat-07','Analyse Prédictive','analyse-predictive',undefined,'on_quote',
    'Modèles d\'analyse prédictive pour anticiper vos ventes, churn clients et comportements d\'achat.','6–12 semaines',false,
    ['Collecte et nettoyage données','Modèle prédictif ML','Dashboard résultats','Alertes automatiques','Formation équipe','Maintenance modèle']),

  /* ══════════ COMMUNITY MANAGEMENT ══════════ */
  p('cm-01','cat-08','Community Management Essentiel','community-management-essentiel',120000,'from',
    '3 publications/semaine sur 2 réseaux sociaux, réponse aux commentaires et rapport mensuel.','Mensuel',true,
    ['3 posts/semaine','2 réseaux sociaux','Création des visuels','Rédaction des légendes','Réponse commentaires','Rapport mensuel']),
  p('cm-02','cat-08','Community Management Premium','community-management-premium',250000,'from',
    '7 publications/semaine sur 4 réseaux, Stories, Reels, modération et stratégie de contenu.','Mensuel',true,
    ['7 posts/semaine','4 réseaux sociaux','Stories quotidiennes','2 Reels/semaine','Modération complète','Stratégie éditoriale mensuelle']),
  p('cm-03','cat-08','Audit Réseaux Sociaux','audit-reseaux-sociaux',50000,'fixed',
    'Analyse complète de vos réseaux : performance, contenu, audience, concurrence et recommandations.','1 semaine',false,
    ['Analyse de chaque réseau','Benchmark concurrentiel','Étude de l\'audience','Performance du contenu','Recommandations actionnables','Plan d\'action 3 mois']),
  p('cm-04','cat-08','Création Compte & Setup','creation-compte-setup',40000,'fixed',
    'Création et optimisation complète de vos comptes réseaux sociaux : profil, bio, visuels, liens.','3–5 jours',false,
    ['Facebook, Instagram, LinkedIn','Optimisation profil complet','Photo de profil et bannière','Bio optimisée SEO','Mise en place pixels','Première publication']),
  p('cm-05','cat-08','Gestion de Crise Réseaux','gestion-crise-reseaux',undefined,'on_quote',
    'Réponse stratégique aux crises et bad buzz sur les réseaux sociaux : contenu, communication, suivi.','Immédiat',false,
    ['Analyse de la crise','Stratégie de réponse','Rédaction contenus apaisants','Modération intensive','Veille 24h/24','Rapport post-crise']),

  /* ══════════ SEO ══════════ */
  p('se-01','cat-09','Audit SEO Complet','audit-seo-complet',80000,'fixed',
    'Analyse technique, contenu et autorité de votre site. Rapport détaillé avec plan d\'action prioritaire.','1 semaine',true,
    ['Audit technique (vitesse, mobile)','Analyse des mots-clés','Étude des backlinks','Analyse de la concurrence','Rapport PDF détaillé','Plan d\'action priorisé']),
  p('se-02','cat-09','SEO On-Page','seo-on-page',100000,'from',
    'Optimisation technique et contenu de votre site pour améliorer son positionnement Google.','2–4 semaines',false,
    ['Optimisation balises title/meta','Structure H1-H6','URLs optimisées','Images alt text','Vitesse de chargement','Linking interne']),
  p('se-03','cat-09','SEO Local Abidjan','seo-local-abidjan',60000,'fixed',
    'Optimisation Google My Business et référencement local pour apparaître dans les recherches de votre zone.','2–3 semaines',true,
    ['Optimisation Google My Business','Mots-clés géolocalisés','Citations locales','Génération d\'avis','Cohérence NAP','Rapport de positionnement']),
  p('se-04','cat-09','Netlinking & Backlinks','netlinking-backlinks',150000,'from',
    'Acquisition de liens entrants de qualité pour renforcer l\'autorité de votre site web sur Google.','Mensuel',false,
    ['Analyse des backlinks actuels','Identification opportunités','Partenariats éditoriaux','Guest posting','Rapport mensuel','Suivi autorité de domaine']),
  p('se-05','cat-09','Création de Contenu SEO','creation-contenu-seo',80000,'from',
    '4 articles de blog optimisés par mois pour attirer un trafic organique qualifié et durable.','Mensuel',false,
    ['Recherche de mots-clés longue traîne','4 articles/mois (800–1500 mots)','Optimisation SEO complète','Images incluses','Maillage interne','Suivi des positions']),

  /* ══════════ HÉBERGEMENT ══════════ */
  p('he-01','cat-10','Hébergement Pro 1 An','hebergement-pro-1-an',60000,'fixed',
    'Hébergement web professionnel SSD, SSL gratuit, sauvegardes quotidiennes et support 24h/24.','Immédiat',true,
    ['Hébergement SSD haute performance','SSL gratuit (HTTPS)','Sauvegardes quotidiennes','Support technique','99.9% de disponibilité','Panneau de contrôle']),
  p('he-02','cat-10','Nom de Domaine + Hébergement','nom-de-domaine-hebergement',80000,'fixed',
    'Enregistrement de votre nom de domaine .com, .ci ou autre + hébergement professionnel 1 an.','Immédiat',true,
    ['Nom de domaine .com ou .ci','Hébergement professionnel','SSL gratuit','Adresses email pro illimitées','DNS managé','Renouvellement simplifié']),
  p('he-03','cat-10','Serveur VPS Dédié','serveur-vps-dedie',150000,'from',
    'Serveur privé virtuel pour sites et applications à forte charge : performance et contrôle total.','2–3 jours',false,
    ['Ressources dédiées','Root access complet','Scalabilité facile','Sauvegardes automatisées','Monitoring 24h/24','IP dédiée']),
  p('he-04','cat-10','Maintenance Site Web Mensuelle','maintenance-site-web-mensuelle',40000,'from',
    'Maintenance préventive mensuelle : mises à jour, sauvegardes, monitoring et rapport d\'état.','Mensuel',false,
    ['Mises à jour CMS et plugins','Sauvegardes testées','Monitoring uptime','Rapport mensuel','Corrections mineures incluses','Support réactif']),
  p('he-05','cat-10','Migration de Site Web','migration-site-web',70000,'from',
    'Migration sécurisée de votre site vers un nouvel hébergeur sans perte de données ni downtime.','1 semaine',false,
    ['Backup complet avant migration','Transfert fichiers et base de données','Configuration DNS','Tests post-migration','Redirection des emails','Zéro downtime']),

  /* ══════════ CYBERSÉCURITÉ ══════════ */
  p('cy-01','cat-11','Audit de Sécurité Site Web','audit-securite-site-web',120000,'fixed',
    'Test de sécurité complet de votre site web : vulnérabilités, failles, recommandations et rapport.','1 semaine',true,
    ['Scan de vulnérabilités','Test d\'injection SQL/XSS','Analyse des configurations','Vérification SSL','Rapport détaillé','Plan de correction priorisé']),
  p('cy-02','cat-11','Protection Anti-Malware','protection-anti-malware',80000,'from',
    'Installation et configuration d\'un pare-feu WAF, antivirus et protection contre les intrusions.','2–5 jours',false,
    ['Pare-feu applicatif (WAF)','Antivirus temps réel','Protection brute force','Blocage IP malveillantes','Monitoring continu','Alertes instantanées']),
  p('cy-03','cat-11','Nettoyage Site Piraté','nettoyage-site-pirate',150000,'fixed',
    'Diagnostic, nettoyage complet et sécurisation d\'un site web piraté ou infecté par un malware.','24–72h',true,
    ['Diagnostic complet','Suppression du malware','Restauration depuis backup','Sécurisation renforcée','Rapport d\'incident','Mesures préventives']),
  p('cy-04','cat-11','Formation Cybersécurité PME','formation-cybersecurite-pme',100000,'fixed',
    'Formation pratique de 4h pour vos équipes : phishing, mots de passe, bonnes pratiques, protocoles.','1 journée',false,
    ['Sensibilisation phishing','Mots de passe sécurisés','2FA et gestionnaire de mots de passe','Sécurité emails','Protocoles en cas d\'incident','Support 30 jours']),
  p('cy-05','cat-11','Conformité RGPD','conformite-rgpd',200000,'from',
    'Mise en conformité de votre site et processus avec le RGPD : politique confidentialité, cookies, registre.','2–4 semaines',false,
    ['Audit de conformité','Politique de confidentialité','Bandeau cookies','Registre de traitement','Procédures RGPD','Formation équipe']),

  /* ══════════ FORMATION ══════════ */
  p('fo-01','cat-12','Formation WordPress','formation-wordpress',80000,'fixed',
    'Formation pratique WordPress : administration, création de pages, blog, et gestion quotidienne.','1 journée',false,
    ['Interface d\'administration','Création et édition de pages','Gestion du blog','Médias et galeries','Plugins essentiels','Support 30 jours']),
  p('fo-02','cat-12','Formation Marketing Digital','formation-marketing-digital',120000,'from',
    'Formation aux fondamentaux du marketing digital : réseaux sociaux, publicité, SEO, email.','1–2 journées',true,
    ['Stratégie digitale','Facebook et Instagram Ads','Google My Business','Email marketing','Analytics et KPIs','Cas pratiques Côte d\'Ivoire']),
  p('fo-03','cat-12','Formation IA pour Entreprises','formation-ia-entreprises',150000,'from',
    'Initiation pratique à l\'IA (ChatGPT, Claude, Midjourney) pour gagner en productivité au quotidien.','1 journée',false,
    ['Bases de l\'IA générative','ChatGPT et Claude au bureau','Génération d\'images','Automatisation tâches','Prompt engineering','Cas d\'usage concrets']),
  p('fo-04','cat-12','Formation E-commerce','formation-ecommerce',120000,'from',
    'Créer et gérer une boutique en ligne rentable : stratégie, produits, paiement, livraison, marketing.','1–2 journées',false,
    ['Business model e-commerce','Création de boutique','Fiche produit qui vend','Paiement Mobile Money','Livraison et logistique','Marketing pour e-commerce']),
  p('fo-05','cat-12','Formation Canva Pro','formation-canva-pro',60000,'fixed',
    'Maîtriser Canva pour créer tous vos visuels professionnels : posts, flyers, présentations, vidéos.','1 journée',false,
    ['Navigation Canva','Templates professionnels','Charte graphique personnalisée','Visuels pour réseaux sociaux','Présentations animées','Exportation et partage']),

  /* ══════════ VIDÉO & CONTENU ══════════ */
  p('vi-01','cat-13','Vidéo Institutionnelle','video-institutionnelle',300000,'from',
    'Film de présentation de votre entreprise : tournage, montage, motion design et musique.','2–4 semaines',true,
    ['Écriture du script','Tournage professionnel','Montage vidéo','Motion design','Musique libre de droits','Sous-titres','Version courte réseaux']),
  p('vi-02','cat-13','Vidéo Publicitaire','video-publicitaire',200000,'from',
    'Spot publicitaire 15–60 secondes pour vos campagnes réseaux sociaux, TV ou cinéma.','1–3 semaines',false,
    ['Concept créatif','Storyboard validé','Tournage ou animation','Montage professionnel','Musique et voix off','Déclinaisons multi-formats']),
  p('vi-03','cat-13','Reels & Shorts','reels-shorts',80000,'from',
    'Création de 8 Reels ou Shorts par mois pour Instagram, TikTok et YouTube. Format viral.','Mensuel',false,
    ['8 vidéos courtes/mois','Sous-titres automatiques','Musique tendance','Textes accrocheurs','Optimisation algorithme','Analyse des performances']),
  p('vi-04','cat-13','Podcast & Audio','podcast-audio',100000,'from',
    'Enregistrement, montage et publication de vos podcasts professionnels sur toutes les plateformes.','Par épisode',false,
    ['Enregistrement studio ou à distance','Montage et nettoyage audio','Jingle intro/outro','Vignette épisode','Publication Spotify/Deezer/Apple','Transcription']),
  p('vi-05','cat-13','Shooting Photo Professionnel','shooting-photo-professionnel',150000,'from',
    'Séance photo professionnelle pour votre entreprise : produits, équipe, locaux, portraits.','1 journée',false,
    ['Photographe professionnel','Retouche et colorimétrie','50 photos HD livrées','Droits d\'utilisation commerciale','Livrables en 7 jours','Version web et print']),
  p('vi-06','cat-13','Motion Design & Animation','motion-design-animation',120000,'from',
    'Animations 2D/3D, logos animés, infographies animées et explainer videos pour votre marque.','1–3 semaines',false,
    ['Logo animé','Explainer video','Infographie animée','Transitions personnalisées','Formats exportés','Fichiers sources']),

  /* ══════════ EMAILING & CRM ══════════ */
  p('em-01','cat-14','Setup Email Marketing','setup-email-marketing',80000,'fixed',
    'Configuration complète de votre outil d\'emailing (Mailchimp, Brevo, SendGrid) et premiers templates.','1 semaine',false,
    ['Choix de l\'outil adapté','Configuration domaine et DKIM','Import de vos contacts','Création de 3 templates','Séquence de bienvenue','Formation utilisation']),
  p('em-02','cat-14','Newsletter Mensuelle','newsletter-mensuelle',60000,'from',
    'Rédaction, design et envoi de votre newsletter mensuelle avec rapport d\'ouvertures et clics.','Mensuel',false,
    ['Rédaction du contenu','Design aux couleurs de votre marque','Segmentation de liste','Envoi et suivi','Rapport taux d\'ouverture','Recommandations']),
  p('em-03','cat-14','Séquence Email Automation','sequence-email-automation',150000,'from',
    'Création de séquences email automatiques : bienvenue, relance panier, fidélisation, rétention.','2–3 semaines',true,
    ['Cartographie du parcours client','5 à 10 emails automatiques','Déclencheurs personnalisés','A/B testing','Rapport performances','Optimisation continue']),
  p('em-04','cat-14','CRM Mise en Place','crm-mise-en-place',200000,'from',
    'Choix, configuration et formation sur votre CRM (HubSpot, Zoho, Pipedrive) pour gérer vos prospects.','2–4 semaines',false,
    ['Choix du CRM adapté','Configuration pipelines','Import données clients','Automatisations commerciales','Formation équipe (4h)','Support 1 mois']),
  p('em-05','cat-14','SMS Marketing','sms-marketing',50000,'from',
    'Campagnes SMS pour vos promotions, rappels et communications urgentes. Taux d\'ouverture > 95%.','Par campagne',false,
    ['Rédaction des SMS','Segmentation contacts','Envoi programmé','Lien court tracké','Opt-out automatique','Rapport livraison']),

  /* ══════════ CONSULTING ══════════ */
  p('co-01','cat-15','Audit Digital Complet','audit-digital-complet',150000,'fixed',
    'Évaluation complète de votre présence digitale : site, réseaux, SEO, publicité, réputation.','1 semaine',true,
    ['Audit site web','Analyse réseaux sociaux','Audit SEO','Performance publicitaire','Réputation en ligne','Plan d\'action priorisé']),
  p('co-02','cat-15','Stratégie de Transformation Digitale','strategie-transformation-digitale',500000,'from',
    'Accompagnement stratégique pour digitaliser votre entreprise : roadmap, outils, équipes, budget.','4–8 semaines',true,
    ['Diagnostic de maturité digitale','Identification des priorités','Sélection des outils','Roadmap sur 12–24 mois','Plan de formation équipes','Suivi trimestriel']),
  p('co-03','cat-15','Conseil en Référencement','conseil-referencement',80000,'fixed',
    'Session de 2h avec un expert SEO pour analyser votre site et définir vos priorités de référencement.','2h',false,
    ['Analyse technique rapide','Opportunités de mots-clés','Conseils contenu','Analyse de la concurrence','Plan d\'action 30 jours','Compte-rendu écrit']),
  p('co-04','cat-15','Business Plan Digital','business-plan-digital',300000,'from',
    'Rédaction de votre business plan digital : marché, concurrence, stratégie, prévisionnel financier.','2–3 semaines',false,
    ['Étude de marché','Analyse concurrentielle','Stratégie marketing','Modèle économique','Prévisionnel 3 ans','Pitch deck']),
  p('co-05','cat-15','Veille Concurrentielle','veille-concurrentielle',100000,'from',
    'Mise en place d\'un système de veille sur vos concurrents : prix, contenu, campagnes, actualités.','Mensuel',false,
    ['Identification des concurrents','Outils de veille configurés','Rapport mensuel automatisé','Alertes Google','Benchmark prix','Recommandations tactiques']),

  /* ══════════ PRINT & SUPPORTS ══════════ */
  p('pr-01','cat-16','Cartes de Visite Premium','cartes-de-visite-premium',35000,'from',
    'Conception graphique de cartes de visite professionnelles. Fichiers prêts à l\'impression.','3–5 jours',false,
    ['Design premium','Recto-verso','Fichiers print HD (CMJN)','3 révisions','Format standard ou personnalisé','Option vernis UV']),
  p('pr-02','cat-16','Flyers & Dépliants','flyers-depliants',30000,'from',
    'Conception de flyers A5/A4, dépliants 3 volets et roll-up pour vos événements et promotions.','3–5 jours',false,
    ['Design aux couleurs de votre marque','Recto-verso','Fichiers print HD','Plusieurs formats','Relecture incluse','Déclinaisons couleurs']),
  p('pr-03','cat-16','Roll-up & Kakémono','rollup-kakemono',45000,'from',
    'Design de roll-up et kakémono pour salons, événements et points de vente. Haute résolution.','3–5 jours',false,
    ['Design grand format','Dimensions standard 85×200cm','Fichiers HD livrés','Option impression et livraison','Adaptation votre charte','Retouches incluses']),
  p('pr-04','cat-16','Brochure d\'Entreprise','brochure-entreprise',100000,'from',
    'Brochure commerciale 8–16 pages pour présenter votre entreprise, services et réalisations.','1–2 semaines',false,
    ['Conception éditoriale','Design complet','Photos libres de droits','8 à 16 pages','Fichier print HD','Version PDF interactif']),
  p('pr-05','cat-16','Papeterie Professionnelle','papeterie-professionnelle',80000,'from',
    'Papier entête, enveloppes, dossiers, tampons et tous vos documents à votre charte graphique.','1 semaine',false,
    ['Papier à en-tête','Enveloppes personnalisées','Chemise à rabat','Tampon entreprise','Signature email','Fichiers prêts impression']),

  /* ══════════ CARTES DIGITALES ══════════ */
  p('cd-01','cat-17','Carte de Visite NFC','carte-de-visite-nfc',25000,'fixed',
    'Carte de visite intelligente NFC : un simple tap transmet vos coordonnées sur n\'importe quel smartphone.','3–5 jours',true,
    ['Puce NFC intégrée','Profil digital complet','Contacts, réseaux, site web','Un tap suffit','Mise à jour sans recréer la carte','Analytics de partage']),
  p('cd-02','cat-17','vCard Pro + QR','vcard-pro-qr',20000,'fixed',
    'Page de profil professionnel en ligne avec QR code : photo, coordonnées, services, réseaux.','2–3 jours',false,
    ['URL personnalisée','Photo professionnelle','Bouton d\'appel et WhatsApp','Réseaux sociaux','Téléchargement vCard','Analytics visiteurs']),
  p('cd-03','cat-17','Carte Digitale Équipe','carte-digitale-equipe',60000,'from',
    'Pack cartes digitales pour toute votre équipe commerciale avec tableau de bord centralisé.','1 semaine',false,
    ['5 à 20 cartes/profils','Dashboard centralisé','Même design pour tous','Mise à jour groupée','Analytics individuels','Signature email']),

  /* ══════════ WHATSAPP BUSINESS ══════════ */
  p('wb-01','cat-18','Configuration WhatsApp Business','configuration-whatsapp-business',30000,'fixed',
    'Configuration complète de WhatsApp Business : profil, catalogue, réponses automatiques, étiquettes.','1–2 jours',true,
    ['Profil entreprise complet','Catalogue produits/services','Message de bienvenue','Message d\'absence','Étiquettes clients','Formation utilisation']),
  p('wb-02','cat-18','WhatsApp API & Automation','whatsapp-api-automation',300000,'from',
    'Intégration de l\'API WhatsApp Business pour des communications automatisées à grande échelle.','2–4 semaines',false,
    ['API officielle Meta','Envoi de messages automatiques','Chatbot intégré','CRM connecté','Templates approuvés','Dashboard d\'envois']),
  p('wb-03','cat-18','Chatbot WhatsApp','chatbot-whatsapp',200000,'from',
    'Chatbot IA sur WhatsApp qui répond à vos clients 24h/24 : commandes, infos, rdv, support.','2–3 semaines',true,
    ['Réponses automatiques intelligentes','FAQ automatisée','Prise de commande','Prise de RDV','Escalade vers humain','Analytics conversations']),
  p('wb-04','cat-18','Stratégie WhatsApp Marketing','strategie-whatsapp-marketing',100000,'from',
    'Stratégie complète et exécution de campagnes marketing WhatsApp : listes, contenus, automation.','Mensuel',false,
    ['Segmentation liste contacts','Calendrier de diffusion','Création des messages','Promotions et offres','Suivi taux d\'ouverture','Rapport mensuel']),
]

export function getStaticProductBySlug(slug: string): Product | undefined {
  return STATIC_PRODUCTS.find(p => p.slug === slug)
}

export function getStaticCategoryBySlug(slug: string): Category | undefined {
  return STATIC_CATEGORIES.find(c => c.slug === slug)
}
