/* ─── DONNÉES COMPLÈTES — 84 TEMPLATES PAR SECTEUR ──────────────────────── */

export interface TemplateItem {
  id: string
  name: string
  tagline: string
  description: string
  primaryColor: string
  accentColor: string
  bgDark: string
  style: 'modern' | 'classic' | 'luxury' | 'bold' | 'warm' | 'minimal' | 'dark' | 'natural' | 'elegant'
  badge?: 'Populaire' | 'Nouveau' | 'Pro' | 'Bestseller'
  features: string[]
  pages: string[]
}

export interface SectorData {
  id: string
  icon: string
  label: string
  color: string
  basePrice: number
  tagline: string
  description: string
  templates: TemplateItem[]
}

export const SECTORS_DATA: SectorData[] = [
  /* ═══════════════════ RESTAURANT ═══════════════════ */
  {
    id: 'restaurant',
    icon: '🍽️',
    label: 'Restaurant & Food',
    color: '#F97316',
    basePrice: 49900,
    tagline: 'Un site web qui donne faim',
    description: 'Templates conçus pour les restaurants, snacks, traiteurs et services de livraison. Présentez votre carte, vos spécialités et recevez des réservations en ligne.',
    templates: [
      {
        id: 'le-gourmet',
        name: 'Le Gourmet',
        tagline: "L'excellence culinaire en ligne",
        description: "Template haut de gamme pour restaurants gastronomiques et tables étoilées. Design sombre et élégant, mise en valeur des plats et de l'expérience.",
        primaryColor: '#D97706',
        accentColor: '#FCD34D',
        bgDark: '#1A0F00',
        style: 'luxury',
        badge: 'Bestseller',
        features: ['Carte interactive multi-catégories', 'Galerie plats en plein écran', 'Réservation table en ligne', 'Présentation chef & équipe', 'Menu du jour dynamique'],
        pages: ['Accueil', 'Notre carte', 'Le chef', 'Réservation', 'Événements', 'Contact'],
      },
      {
        id: 'street-food',
        name: 'Street Food',
        tagline: 'Rapide, savoureux, irrésistible',
        description: 'Template dynamique et coloré pour fast-food, snacks et restaurants de rue. Commandes en ligne, click & collect et livraison intégrés.',
        primaryColor: '#EF4444',
        accentColor: '#FFA500',
        bgDark: '#1A0000',
        style: 'bold',
        badge: 'Populaire',
        features: ['Menu digital affiché', 'Commande en ligne / livraison', 'Click & collect', 'Avis Google intégrés', 'Promotions et offres'],
        pages: ['Accueil', 'Commander', 'Notre menu', 'Offres', 'Contact'],
      },
      {
        id: 'traiteur',
        name: 'Traiteur Premium',
        tagline: 'Vos événements, notre passion',
        description: "Template professionnel pour services de traiteur, organisation de banquets et restauration d'entreprise. Devis en ligne et galerie réalisations.",
        primaryColor: '#7C3AED',
        accentColor: '#C4B5FD',
        bgDark: '#0D001A',
        style: 'elegant',
        features: ['Catalogue prestations traiteur', 'Demande de devis événement', 'Galerie réalisations', 'Menus personnalisables', 'Témoignages clients'],
        pages: ['Accueil', 'Nos prestations', 'Galerie', 'Demander un devis', 'Contact'],
      },
      {
        id: 'brasserie',
        name: 'Brasserie & Bar',
        tagline: 'Ambiance chaleureuse, saveurs authentiques',
        description: "Template warm et accueillant pour brasseries, bars et bistros. Carte des boissons, événements live et ambiance mise en avant.",
        primaryColor: '#92400E',
        accentColor: '#FDE68A',
        bgDark: '#180A00',
        style: 'warm',
        badge: 'Nouveau',
        features: ["Carte bières et cocktails", 'Événements & soirées live', 'Happy hour dynamique', 'Réservation de tables', 'Programme fidélité'],
        pages: ['Accueil', 'La carte', 'Événements', 'Réservation', 'Contact'],
      },
      {
        id: 'pizza-express',
        name: 'Pizza Express',
        tagline: 'Livraison en 30 minutes chrono',
        description: "Template optimisé pour pizzerias et restaurants de livraison. Interface de commande rapide, suivi de livraison et personnalisation des pizzas.",
        primaryColor: '#DC2626',
        accentColor: '#FCA5A5',
        bgDark: '#1A0000',
        style: 'bold',
        features: ['Configurateur de pizza en ligne', 'Commande et livraison', 'Zones de livraison', 'Suivi commande', 'Carte de fidélité'],
        pages: ['Accueil', 'Commander', 'Notre carte', 'Suivi', 'Contact'],
      },
      {
        id: 'afro-cuisine',
        name: 'Afro Cuisine',
        tagline: "La richesse des saveurs africaines",
        description: "Template vibrant et coloré pour restaurants de cuisine africaine et antillaise. Valorise les saveurs, les épices et l'authenticité culturelle.",
        primaryColor: '#16A34A',
        accentColor: '#FCD34D',
        bgDark: '#001A08',
        style: 'warm',
        badge: 'Nouveau',
        features: ['Carte spécialités africaines', 'Histoire et culture culinaire', 'Galerie plats typiques', 'Ateliers cuisine', 'Traiteur événements'],
        pages: ['Accueil', 'La carte', 'Notre histoire', 'Galerie', 'Ateliers', 'Contact'],
      },
      {
        id: 'cafe-bistro',
        name: 'Café & Bistro',
        tagline: 'Votre pause café préférée',
        description: "Template cosy et moderne pour cafés, salons de thé et petits bistrots. Carte des boissons, pâtisseries et ambiance mise en valeur.",
        primaryColor: '#78350F',
        accentColor: '#E9C46A',
        bgDark: '#12060000',
        style: 'classic',
        features: ['Carte cafés & pâtisseries', 'Espace Wi-Fi & coworking', 'Réservation privatisation', 'Programme fidélité', 'Click & collect'],
        pages: ['Accueil', 'Notre carte', 'Espace', 'Privatisation', 'Contact'],
      },
      {
        id: 'food-delivery',
        name: 'Food Delivery',
        tagline: 'Commandez, on livre partout',
        description: "Template centré sur la livraison à domicile pour dark kitchens et restaurants de livraison. Interface UX optimisée pour la conversion.",
        primaryColor: '#0891B2',
        accentColor: '#67E8F9',
        bgDark: '#00111A',
        style: 'modern',
        badge: 'Populaire',
        features: ['Catalogue multi-cuisines', 'Commande & tracking', 'Zones de livraison carte', 'Notifications SMS', 'Application mobile ready'],
        pages: ['Accueil', 'Commander', 'Suivre ma commande', 'Offres', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ IMMOBILIER ═══════════════════ */
  {
    id: 'immobilier',
    icon: '🏠',
    label: 'Immobilier',
    color: '#3B82F6',
    basePrice: 79900,
    tagline: 'Vendez et louez plus vite en ligne',
    description: 'Templates professionnels pour agences immobilières, promoteurs et agents indépendants. Publiez vos annonces, qualifiez vos prospects et boostez vos ventes.',
    templates: [
      {
        id: 'premium-realty',
        name: 'Premium Realty',
        tagline: "L'immobilier de prestige",
        description: "Template luxe pour agences spécialisées en biens de prestige. Design épuré, photos plein écran et expérience client premium.",
        primaryColor: '#1D4ED8',
        accentColor: '#93C5FD',
        bgDark: '#00061A',
        style: 'luxury',
        badge: 'Bestseller',
        features: ['Catalogue biens premium', 'Visite virtuelle 360°', 'Estimation en ligne', 'Espace investisseurs', 'Alertes nouvelles propriétés'],
        pages: ['Accueil', 'Nos biens', 'Estimation', 'Investissement', 'Équipe', 'Contact'],
      },
      {
        id: 'urban-habitat',
        name: 'Urban Habitat',
        tagline: 'Votre habitat urbain idéal',
        description: "Template moderne pour promoteurs immobiliers et agences en zone urbaine. Présentation de projets neufs et plans d'appartements.",
        primaryColor: '#0369A1',
        accentColor: '#7DD3FC',
        bgDark: '#000D1A',
        style: 'modern',
        badge: 'Populaire',
        features: ["Plans d'appartements interactifs", 'Projets en cours & livrés', 'Simulateur de financement', 'Réservation en ligne', 'Visite de chantier'],
        pages: ['Accueil', 'Nos programmes', 'Appartements', 'Financement', 'Contact'],
      },
      {
        id: 'villa-prestige',
        name: 'Villa Prestige',
        tagline: 'Villas et résidences d\'exception',
        description: "Template élégant pour la vente et location de villas, résidences et propriétés haut de gamme avec piscine et jardins.",
        primaryColor: '#0F766E',
        accentColor: '#5EEAD4',
        bgDark: '#001A17',
        style: 'luxury',
        badge: 'Pro',
        features: ['Galerie immersive par propriété', 'Visite virtuelle 3D', 'Recherche avancée', 'Alerte bien disponible', 'Contact agent dédié'],
        pages: ['Accueil', 'Villas', 'Résidences', 'Location', 'Contact'],
      },
      {
        id: 'agence-locale',
        name: 'Agence Locale',
        tagline: 'Votre spécialiste du quartier',
        description: "Template accessible et professionnel pour petites agences immobilières locales. Annonces, carte interactive et contact facile.",
        primaryColor: '#2563EB',
        accentColor: '#BFDBFE',
        bgDark: '#00061A',
        style: 'classic',
        features: ['Annonces vente & location', 'Carte interactive des biens', "Estimation gratuite en ligne", 'Blog marché immobilier', 'Équipe et mandats'],
        pages: ['Accueil', 'Vente', 'Location', 'Estimation', 'Blog', 'Contact'],
      },
      {
        id: 'invest-immo',
        name: 'Invest Immo',
        tagline: 'Faites fructifier votre patrimoine',
        description: "Template orienté investissement pour promoteurs et conseillers en patrimoine immobilier. Rendements, projets et accompagnement.",
        primaryColor: '#4338CA',
        accentColor: '#C7D2FE',
        bgDark: '#030014',
        style: 'dark',
        badge: 'Pro',
        features: ['Projets d\'investissement', 'Calculateur de rendement', 'Patrimoine & défiscalisation', 'Webinaires investisseurs', 'Tableau de bord investisseur'],
        pages: ['Accueil', 'Nos projets', 'Simulateur', 'Actualités', 'Espace investisseur', 'Contact'],
      },
      {
        id: 'location-vacances',
        name: 'Location Vacances',
        tagline: 'Louez plus, gérez moins',
        description: "Template pour propriétaires et gestionnaires de locations saisonnières. Calendrier de disponibilités et réservations directes sans commission.",
        primaryColor: '#0891B2',
        accentColor: '#A5F3FC',
        bgDark: '#00101A',
        style: 'warm',
        badge: 'Nouveau',
        features: ['Calendrier de disponibilités', 'Réservation directe en ligne', 'Photos & vidéo immersive', 'Avis locataires', 'Guide du séjour'],
        pages: ['Accueil', 'Nos locations', 'Disponibilités', 'Avis', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ SANTÉ ═══════════════════ */
  {
    id: 'sante',
    icon: '🏥',
    label: 'Santé & Clinique',
    color: '#10B981',
    basePrice: 59900,
    tagline: 'La confiance commence sur votre site',
    description: 'Templates rassurants pour cliniques, cabinets médicaux, pharmacies et laboratoires. Gérez les prises de rendez-vous et informez vos patients efficacement.',
    templates: [
      {
        id: 'clinique-sante',
        name: 'Clinique Santé',
        tagline: 'Votre santé, notre priorité',
        description: "Template complet pour cliniques pluridisciplinaires et centres médicaux. Spécialités, médecins, rendez-vous et informations patients.",
        primaryColor: '#059669',
        accentColor: '#6EE7B7',
        bgDark: '#001A0D',
        style: 'modern',
        badge: 'Bestseller',
        features: ['Présentation multi-spécialités', 'Trombinoscope médecins', 'RDV en ligne 24h/24', 'Urgences et horaires', 'Actualités santé'],
        pages: ['Accueil', 'Spécialités', 'Médecins', 'Rendez-vous', 'Patients', 'Contact'],
      },
      {
        id: 'dentaire-pro',
        name: 'Dentaire Pro',
        tagline: 'Sourires impeccables, confiance totale',
        description: "Template spécialisé pour cabinets dentaires et orthodontistes. Design épuré, avant/après et prise de RDV optimisée.",
        primaryColor: '#0284C7',
        accentColor: '#7DD3FC',
        bgDark: '#000D1A',
        style: 'minimal',
        badge: 'Populaire',
        features: ['Galerie avant/après soins', 'Présentation des traitements', 'RDV en ligne par praticien', 'Tarifs et remboursements', 'Urgences dentaires'],
        pages: ['Accueil', 'Nos soins', "L'équipe", 'Tarifs', 'Rendez-vous', 'Contact'],
      },
      {
        id: 'pharmacie-plus',
        name: 'Pharmacie Plus',
        tagline: 'Votre pharmacie de confiance',
        description: "Template moderne pour pharmacies et parapharmacies. Catalogue produits, conseils santé et services de livraison à domicile.",
        primaryColor: '#16A34A',
        accentColor: '#86EFAC',
        bgDark: '#001A08',
        style: 'classic',
        features: ['Catalogue médicaments & parapharmacie', 'Conseils santé par catégorie', 'Ordonnance en ligne', 'Livraison à domicile', 'Actualités & prévention'],
        pages: ['Accueil', 'Nos produits', 'Services', 'Conseils', 'Ordonnance', 'Contact'],
      },
      {
        id: 'kine-sport',
        name: 'Kiné & Sport',
        tagline: 'Récupérez, performez, dépassez-vous',
        description: "Template dynamique pour kinésithérapeutes, ostéopathes et médecins du sport. Cabinet de soins et suivi de performance sportive.",
        primaryColor: '#2563EB',
        accentColor: '#93C5FD',
        bgDark: '#00061A',
        style: 'bold',
        badge: 'Nouveau',
        features: ['Techniques et spécialités', 'RDV par praticien', 'Suivi patient en ligne', 'Conseils récupération', 'Sport & performance'],
        pages: ['Accueil', 'Nos soins', 'Praticiens', 'Rendez-vous', 'Contact'],
      },
      {
        id: 'maternite',
        name: 'Maternité & Pédiatrie',
        tagline: 'Accompagner chaque vie dès le premier jour',
        description: "Template doux et rassurant pour maternités, pédiatres et gynécologues. Suivi de grossesse, carnet de santé et consultations.",
        primaryColor: '#DB2777',
        accentColor: '#FBCFE8',
        bgDark: '#1A0010',
        style: 'warm',
        features: ['Suivi grossesse & maternité', 'Carnet de santé enfant', 'RDV pédiatre en ligne', 'Ressources pour parents', 'Urgences pédiatriques'],
        pages: ['Accueil', 'Maternité', 'Pédiatrie', 'Rendez-vous', 'Parents', 'Contact'],
      },
      {
        id: 'labo-analyse',
        name: 'Laboratoire',
        tagline: 'Résultats précis, service rapide',
        description: "Template professionnel pour laboratoires d'analyses médicales et centres de biologie. Résultats en ligne et prises en charge.",
        primaryColor: '#7C3AED',
        accentColor: '#C4B5FD',
        bgDark: '#0D001A',
        style: 'modern',
        badge: 'Pro',
        features: ['Analyses disponibles par spécialité', 'Résultats en ligne sécurisés', 'Prise en charge mutuelles', 'Horaires & adresses', 'Préparation aux analyses'],
        pages: ['Accueil', 'Nos analyses', 'Résultats', 'Prises en charge', 'Contact'],
      },
      {
        id: 'medecine-naturelle',
        name: 'Médecine Naturelle',
        tagline: 'La santé par la nature',
        description: "Template apaisant pour praticiens en médecine douce, naturopathes et thérapeutes. Approche holistique et bien-être.",
        primaryColor: '#65A30D',
        accentColor: '#BEF264',
        bgDark: '#061A00',
        style: 'natural',
        badge: 'Nouveau',
        features: ['Présentation des disciplines', 'Consultation & bilan de santé', 'Blog bien-être & naturo', 'Boutique produits naturels', 'Ateliers & retraites'],
        pages: ['Accueil', 'Nos soins', 'Praticiens', 'Boutique', 'Blog', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ FORMATION ═══════════════════ */
  {
    id: 'formation',
    icon: '🎓',
    label: 'Formation & École',
    color: '#8B5CF6',
    basePrice: 59900,
    tagline: "Attirez plus d'apprenants en ligne",
    description: 'Templates conçus pour centres de formation, écoles privées, auto-écoles et organismes de certification. Présentez vos programmes et recevez des inscriptions.',
    templates: [
      {
        id: 'ecole-business',
        name: 'École de Commerce',
        tagline: 'Formez les leaders de demain',
        description: "Template premium pour écoles de commerce, MBA et grandes écoles. Classement, alumni et valeur ajoutée mis en avant.",
        primaryColor: '#6D28D9',
        accentColor: '#DDD6FE',
        bgDark: '#0D001A',
        style: 'luxury',
        badge: 'Pro',
        features: ['Programmes MBA & masters', 'Témoignages alumni', 'Classements & accréditations', 'Portes ouvertes & événements', 'Espace candidats'],
        pages: ['Accueil', 'Programmes', 'Admissions', 'Alumni', 'Actualités', 'Contact'],
      },
      {
        id: 'formation-pro',
        name: 'Centre de Formation Pro',
        tagline: 'Montez en compétences, évoluez',
        description: "Template complet pour centres de formation professionnelle et organismes certifiants. Catalogue, planning et inscriptions.",
        primaryColor: '#7C3AED',
        accentColor: '#C4B5FD',
        bgDark: '#0D001A',
        style: 'modern',
        badge: 'Bestseller',
        features: ['Catalogue formations CPF', 'Planning des sessions', 'Inscription en ligne', 'Financement & OPCO', 'Certification & attestations'],
        pages: ['Accueil', 'Nos formations', 'Planning', 'Financement', 'Inscription', 'Contact'],
      },
      {
        id: 'auto-ecole',
        name: "Auto-École Moderne",
        tagline: 'Le permis en toute confiance',
        description: "Template dynamique pour auto-écoles. Tarifs, moniteurs, code en ligne et suivi de progression des élèves.",
        primaryColor: '#EA580C',
        accentColor: '#FDBA74',
        bgDark: '#1A0800',
        style: 'bold',
        badge: 'Populaire',
        features: ['Formules permis B, A, C', 'Moniteurs & planning', 'Code en ligne intégré', 'Suivi heures de conduite', 'Tarifs & financement'],
        pages: ['Accueil', 'Nos formules', 'Moniteurs', 'Code en ligne', 'Inscription', 'Contact'],
      },
      {
        id: 'universite-privee',
        name: 'Université Privée',
        tagline: "L'excellence académique pour tous",
        description: "Template institutionnel pour universités privées et instituts supérieurs. Filières, admissions et vie campus.",
        primaryColor: '#1D4ED8',
        accentColor: '#BFDBFE',
        bgDark: '#00061A',
        style: 'classic',
        features: ['Filières & programmes', 'Vie sur le campus', 'Admissions & concours', 'Recherche & publications', 'Partenariats entreprises'],
        pages: ['Accueil', 'Filières', 'Campus', 'Admissions', 'Recherche', 'Contact'],
      },
      {
        id: 'tutorat-scolaire',
        name: 'Tutorat Scolaire',
        tagline: 'Accompagnons chaque élève vers le succès',
        description: "Template chaleureux pour centres de soutien scolaire, tutorat et coaching académique de la primaire au lycée.",
        primaryColor: '#0891B2',
        accentColor: '#A5F3FC',
        bgDark: '#00101A',
        style: 'warm',
        badge: 'Nouveau',
        features: ['Matières & niveaux', 'Profils des tuteurs', 'Cours particuliers & groupes', 'Résultats & témoignages', 'Inscription & essai gratuit'],
        pages: ['Accueil', 'Nos cours', 'Tuteurs', 'Résultats', 'Inscription', 'Contact'],
      },
      {
        id: 'formation-digitale',
        name: 'Formation Digitale',
        tagline: 'Apprenez le digital, changez votre vie',
        description: "Template moderne pour centres de formation numérique, coding bootcamps et écoles de marketing digital.",
        primaryColor: '#0F172A',
        accentColor: '#38BDF8',
        bgDark: '#020819',
        style: 'dark',
        badge: 'Populaire',
        features: ['Formations tech & marketing', 'Bootcamps intensifs', 'Portfolio étudiants', 'Placement entreprises', 'Cours en ligne & présentiel'],
        pages: ['Accueil', 'Formations', 'Programme', 'Placement', 'Actualités', 'Contact'],
      },
      {
        id: 'academie-langues',
        name: "Académie des Langues",
        tagline: 'Parlez le monde entier',
        description: "Template coloré et international pour écoles de langues et académies. Cours, certifications et immersion linguistique.",
        primaryColor: '#DC2626',
        accentColor: '#FCA5A5',
        bgDark: '#1A0000',
        style: 'modern',
        features: ['Langues & niveaux proposés', 'Certifications DELF, TOEFL…', 'Cours intensifs & extensifs', 'E-learning intégré', 'Échanges linguistiques'],
        pages: ['Accueil', 'Langues', 'Certifications', 'Planning', 'Inscription', 'Contact'],
      },
      {
        id: 'ecole-art',
        name: "École des Arts",
        tagline: 'Exprimez votre talent',
        description: "Template créatif et artistique pour écoles de beaux-arts, conservatoires et académies de danse ou musique.",
        primaryColor: '#9333EA',
        accentColor: '#E9D5FF',
        bgDark: '#110024',
        style: 'elegant',
        badge: 'Nouveau',
        features: ['Disciplines & ateliers', 'Portfolio étudiants', 'Spectacles & expositions', 'Inscriptions & auditions', 'Galerie des œuvres'],
        pages: ['Accueil', 'Disciplines', 'Galerie', 'Événements', 'Inscription', 'Contact'],
      },
      {
        id: 'coaching-carriere',
        name: 'Coaching Carrière',
        tagline: 'Construisez la carrière que vous méritez',
        description: "Template professionnel pour coachs carrière, cabinets de recrutement et consultants en orientation professionnelle.",
        primaryColor: '#0F766E',
        accentColor: '#5EEAD4',
        bgDark: '#001A17',
        style: 'minimal',
        badge: 'Pro',
        features: ['Programmes de coaching', 'Bilan de compétences', 'CV & entretiens', 'Témoignages coachés', 'Consultation individuelle en ligne'],
        pages: ['Accueil', 'Programmes', 'Coach', 'Témoignages', 'Réserver', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ E-COMMERCE ═══════════════════ */
  {
    id: 'ecommerce',
    icon: '🛒',
    label: 'E-commerce',
    color: '#EF4444',
    basePrice: 99900,
    tagline: 'Vendez partout, 24h/24',
    description: 'Templates e-commerce complets pour boutiques en ligne, revendeurs et créateurs. Gérez votre catalogue, recevez des paiements Mobile Money et développez vos ventes.',
    templates: [
      {
        id: 'boutique-mode',
        name: 'Boutique Mode',
        tagline: 'La mode africaine en ligne',
        description: "Template élégant pour boutiques de prêt-à-porter, vêtements et accessoires. Lookbooks, tailles et collections saisonnières.",
        primaryColor: '#BE185D',
        accentColor: '#FBCFE8',
        bgDark: '#1A0010',
        style: 'elegant',
        badge: 'Bestseller',
        features: ['Catalogue mode avec filtres', 'Lookbook saisonnier', 'Tailles & guide des tailles', 'Wishlist & partage', 'Paiement Mobile Money'],
        pages: ['Accueil', 'Nouveautés', 'Femme', 'Homme', 'Accessoires', 'Panier', 'Contact'],
      },
      {
        id: 'tech-store',
        name: 'Tech Store',
        tagline: "La tech à portée de clic",
        description: "Template moderne pour boutiques d'électronique, smartphones et accessoires tech. Comparaison produits et garanties intégrées.",
        primaryColor: '#1D4ED8',
        accentColor: '#93C5FD',
        bgDark: '#00061A',
        style: 'dark',
        badge: 'Populaire',
        features: ['Catalogue tech & specs', 'Comparaison produits', 'Garantie & SAV', 'Avis clients vérifiés', 'Paiement en plusieurs fois'],
        pages: ['Accueil', 'Smartphones', 'Informatique', 'Accessoires', 'SAV', 'Contact'],
      },
      {
        id: 'cosmetique-shop',
        name: 'Cosmétique Shop',
        tagline: 'Beauté naturelle, livrée chez vous',
        description: "Template luxe pour boutiques de cosmétiques, soins beauté et produits naturels. Quiz beauté et recommandations personnalisées.",
        primaryColor: '#9333EA',
        accentColor: '#D8B4FE',
        bgDark: '#110024',
        style: 'luxury',
        features: ['Catalogue soins & maquillage', 'Quiz beauté personnalisé', 'Abonnement box beauté', 'Avis & notes produits', 'Guide ingrédients naturels'],
        pages: ['Accueil', 'Soins', 'Maquillage', 'Naturel & Bio', 'Blog', 'Contact'],
      },
      {
        id: 'alimentaire',
        name: 'Épicerie & Alimentation',
        tagline: 'Le meilleur de votre terroir livré',
        description: "Template frais et coloré pour épiceries en ligne, circuits courts et produits alimentaires artisanaux.",
        primaryColor: '#16A34A',
        accentColor: '#86EFAC',
        bgDark: '#001A08',
        style: 'natural',
        badge: 'Nouveau',
        features: ['Catalogue produits frais', 'Commande abonnement hebdo', 'Origine & traçabilité', 'Recettes & suggestions', 'Livraison sous 24h'],
        pages: ['Accueil', 'Nos produits', 'Producteurs', 'Recettes', 'Commander', 'Contact'],
      },
      {
        id: 'artisanat',
        name: "Artisanat Local",
        tagline: "Savoir-faire africain, marché mondial",
        description: "Template chaleureux pour artisans, créateurs locaux et marketplace artisanale. Mise en valeur du savoir-faire et de l'authenticité.",
        primaryColor: '#B45309',
        accentColor: '#FDE68A',
        bgDark: '#180800',
        style: 'warm',
        badge: 'Populaire',
        features: ['Boutique artisan individuel', 'Histoire & processus création', 'Personnalisation commandes', 'Expédition internationale', 'Certification artisan'],
        pages: ['Accueil', 'Collections', 'Artisans', 'Sur mesure', 'Histoire', 'Contact'],
      },
      {
        id: 'sport-fitness',
        name: 'Sport & Fitness',
        tagline: 'Équipez-vous pour dépasser vos limites',
        description: "Template dynamique pour boutiques d'équipements sportifs et nutrition fitness. Conseil expert et programmes d'entraînement.",
        primaryColor: '#EA580C',
        accentColor: '#FDBA74',
        bgDark: '#1A0800',
        style: 'bold',
        features: ['Équipements par sport', 'Nutrition & compléments', 'Programmes entraînement', 'Avis athlètes', 'Livraison express'],
        pages: ['Accueil', 'Équipements', 'Nutrition', 'Programmes', 'Blog', 'Contact'],
      },
      {
        id: 'maison-deco',
        name: 'Maison & Déco',
        tagline: "Décorez votre intérieur avec style",
        description: "Template élégant pour boutiques de décoration intérieure, mobilier design et accessoires maison. Ambiances et inspiration.",
        primaryColor: '#78350F',
        accentColor: '#FDE68A',
        bgDark: '#120600',
        style: 'elegant',
        badge: 'Nouveau',
        features: ['Catalogue déco & mobilier', 'Ambiances & moodboards', 'Configurateur intérieur', 'Livraison & montage', 'Conseils décorateur'],
        pages: ['Accueil', 'Salon', 'Chambre', 'Cuisine', 'Jardin', 'Contact'],
      },
      {
        id: 'fleuriste',
        name: 'Fleuriste & Cadeaux',
        tagline: 'Envoyez des émotions fleuries',
        description: "Template doux pour fleuristes, bouquetiers et boutiques de cadeaux. Livraison occasion spéciale et abonnement floral.",
        primaryColor: '#BE185D',
        accentColor: '#FCE7F3',
        bgDark: '#1A0010',
        style: 'elegant',
        features: ['Catalogue bouquets & fleurs', 'Livraison même jour', 'Événements & mariages', 'Abonnement floral', 'Message personnalisé'],
        pages: ['Accueil', 'Bouquets', 'Cadeaux', 'Mariages', 'Abonnement', 'Contact'],
      },
      {
        id: 'livres-culture',
        name: 'Livres & Culture',
        tagline: "La librairie africaine en ligne",
        description: "Template culturel et chaleureux pour librairies, distributeurs de livres africains et maisons d'édition.",
        primaryColor: '#92400E',
        accentColor: '#FDE68A',
        bgDark: '#180A00',
        style: 'warm',
        features: ['Catalogue livres par genre', 'Auteurs africains mis en avant', 'Clubs de lecture', 'Événements & dédicaces', 'Livraison & ebooks'],
        pages: ['Accueil', 'Catalogue', 'Auteurs', 'Événements', 'Blog', 'Contact'],
      },
      {
        id: 'multi-boutique',
        name: 'Multi-Boutique',
        tagline: 'Tout ce dont vous avez besoin, au même endroit',
        description: "Template marketplace polyvalent pour boutiques multi-catégories et grands magasins en ligne. Puissant et flexible.",
        primaryColor: '#0F172A',
        accentColor: '#38BDF8',
        bgDark: '#020819',
        style: 'modern',
        badge: 'Pro',
        features: ['Multi-catégories & départements', 'Moteur de recherche avancé', 'Sellers multiples (option)', 'Promotions & ventes flash', 'Programme fidélité'],
        pages: ['Accueil', 'Catégories', 'Promotions', 'Mon compte', 'Panier', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ BTP ═══════════════════ */
  {
    id: 'btp',
    icon: '🏗️',
    label: 'BTP & Construction',
    color: '#F59E0B',
    basePrice: 69900,
    tagline: 'Montrez vos réalisations, décrochez des chantiers',
    description: 'Templates solides pour entreprises BTP, architectes, promoteurs et artisans du bâtiment. Valorisez vos chantiers et recevez des demandes de devis qualifiées.',
    templates: [
      {
        id: 'construction-elite',
        name: 'Construction Elite',
        tagline: 'Bâtir avec excellence',
        description: "Template premium pour entreprises de construction gros œuvre, génie civil et bâtiments industriels. Références et capacités techniques.",
        primaryColor: '#D97706',
        accentColor: '#FCD34D',
        bgDark: '#1A0F00',
        style: 'bold',
        badge: 'Bestseller',
        features: ['Portfolio chantiers avec photos', 'Références & clients grands comptes', 'Matériaux & procédés', 'Demande de devis technique', 'Certifications & normes'],
        pages: ['Accueil', 'Nos réalisations', 'Services', 'Devis', 'Certifications', 'Contact'],
      },
      {
        id: 'renovation-habitat',
        name: 'Rénovation Habitat',
        tagline: 'Transformez votre intérieur',
        description: "Template pour artisans et entreprises de rénovation intérieure. Avant/après percutants et devis en ligne.",
        primaryColor: '#B45309',
        accentColor: '#FDE68A',
        bgDark: '#180800',
        style: 'warm',
        badge: 'Populaire',
        features: ['Photos avant/après chantiers', 'Services par corps de métier', 'Simulateur budget rénovation', 'Devis gratuit en ligne', 'Avis clients vérifiés'],
        pages: ['Accueil', 'Réalisations', 'Services', 'Devis gratuit', 'Avis', 'Contact'],
      },
      {
        id: 'architecture',
        name: 'Architecture & Design',
        tagline: 'Concevoir des espaces de vie',
        description: "Template élégant et minimaliste pour cabinets d'architecture, bureaux d'études et designers d'intérieur.",
        primaryColor: '#374151',
        accentColor: '#D1D5DB',
        bgDark: '#060810',
        style: 'minimal',
        badge: 'Pro',
        features: ['Portfolio projets architecturaux', 'Plans & 3D rendus', 'Processus de conception', 'Approche durable & écologique', 'Demande de consultation'],
        pages: ['Accueil', 'Portfolio', 'Services', 'Studio', 'Blog', 'Contact'],
      },
      {
        id: 'electricite-plomberie',
        name: 'Électricité & Plomberie',
        tagline: 'Dépannage rapide, travaux garantis',
        description: "Template pratique pour électriciens, plombiers et artisans multi-services. Intervention rapide et devis express.",
        primaryColor: '#1D4ED8',
        accentColor: '#BFDBFE',
        bgDark: '#00061A',
        style: 'classic',
        features: ['Services & urgences 24h/24', 'Zone d\'intervention', 'Demande d\'intervention en ligne', 'Avis clients', 'Garanties et assurances'],
        pages: ['Accueil', 'Nos services', 'Urgences', 'Devis', 'Avis', 'Contact'],
      },
      {
        id: 'paysagiste',
        name: 'Paysagiste & Jardinage',
        tagline: 'Votre jardin, notre chef-d\'œuvre',
        description: "Template naturel pour paysagistes, jardiniers professionnels et entreprises d'espaces verts. Portfolio jardin et entretien.",
        primaryColor: '#15803D',
        accentColor: '#86EFAC',
        bgDark: '#001A08',
        style: 'natural',
        badge: 'Nouveau',
        features: ['Portfolio jardins réalisés', 'Services entretien régulier', 'Aménagement espaces verts', 'Devis en ligne', 'Saisons & conseils jardinage'],
        pages: ['Accueil', 'Nos réalisations', 'Services', 'Entretien', 'Devis', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ CABINET ═══════════════════ */
  {
    id: 'cabinet',
    icon: '⚖️',
    label: 'Cabinet & Conseil',
    color: '#06B6D4',
    basePrice: 59900,
    tagline: 'La crédibilité en ligne dès le premier clic',
    description: "Templates sobres et professionnels pour cabinets d'avocats, experts-comptables, consultants et conseillers. Générez de la confiance et convertissez vos prospects.",
    templates: [
      {
        id: 'cabinet-avocat',
        name: "Cabinet d'Avocats",
        tagline: 'Défendre vos droits, protéger vos intérêts',
        description: "Template sobre et crédible pour cabinets d'avocats, barreaux et juristes. Domaines de droit, avocats associés et consultation en ligne.",
        primaryColor: '#0E7490',
        accentColor: '#A5F3FC',
        bgDark: '#001218',
        style: 'classic',
        badge: 'Bestseller',
        features: ['Domaines du droit', "Profils des avocats associés", 'Consultation en ligne', 'Actualités juridiques', 'Honoraires & devis'],
        pages: ['Accueil', 'Domaines', "L'équipe", 'Actualités', 'Consultation', 'Contact'],
      },
      {
        id: 'expert-comptable',
        name: 'Expert-Comptable',
        tagline: 'Votre partenaire financier de confiance',
        description: "Template rigoureux pour experts-comptables, commissaires aux comptes et cabinets d'audit. Missions, équipe et ressources.",
        primaryColor: '#1D4ED8',
        accentColor: '#BFDBFE',
        bgDark: '#00061A',
        style: 'minimal',
        badge: 'Pro',
        features: ['Missions comptables & fiscales', 'Équipe experts', 'Ressources & guides', 'Simulation fiscale', 'Espace client sécurisé'],
        pages: ['Accueil', 'Nos missions', 'Équipe', 'Ressources', 'Espace client', 'Contact'],
      },
      {
        id: 'consultant-rh',
        name: 'Consultant RH',
        tagline: "L'humain au cœur de votre performance",
        description: "Template professionnel pour cabinets RH, recruteurs et consultants en management. Recrutement, formation et conseil RH.",
        primaryColor: '#7C3AED',
        accentColor: '#DDD6FE',
        bgDark: '#0D001A',
        style: 'modern',
        badge: 'Nouveau',
        features: ['Services RH & recrutement', 'Formation & développement', 'Audit social', 'Offres d\'emploi', 'Bilan de compétences'],
        pages: ['Accueil', 'Services', 'Recrutement', 'Offres', 'Ressources', 'Contact'],
      },
      {
        id: 'agence-com',
        name: 'Agence de Communication',
        tagline: 'Votre marque, amplifiée',
        description: "Template créatif pour agences de communication, marketing digital et relations publiques. Portfolio et études de cas.",
        primaryColor: '#EA580C',
        accentColor: '#FDBA74',
        bgDark: '#1A0800',
        style: 'bold',
        badge: 'Populaire',
        features: ['Portfolio clients & réalisations', 'Services 360° marketing', 'Études de cas', 'Blog marketing', 'Brief projet en ligne'],
        pages: ['Accueil', 'Services', 'Portfolio', 'Cas clients', 'Blog', 'Contact'],
      },
      {
        id: 'bureau-etudes',
        name: "Bureau d'Études",
        tagline: 'Expertise technique, résultats concrets',
        description: "Template professionnel pour bureaux d'études, ingénierie conseil et cabinets techniques. Expertises et références projets.",
        primaryColor: '#374151',
        accentColor: '#9CA3AF',
        bgDark: '#060810',
        style: 'dark',
        features: ['Domaines d\'expertise technique', 'Références projets', 'Équipe ingénieurs', 'Normes & certifications', 'Appel d\'offres'],
        pages: ['Accueil', 'Expertises', 'Références', 'Équipe', 'Certifications', 'Contact'],
      },
      {
        id: 'notariat',
        name: 'Notariat & Juridique',
        tagline: 'Sécuriser vos actes, garantir vos droits',
        description: "Template sobre et rassurant pour notaires, huissiers et professionnels du droit. Actes, conseils et rendez-vous.",
        primaryColor: '#1E3A5F',
        accentColor: '#93C5FD',
        bgDark: '#000A18',
        style: 'classic',
        badge: 'Pro',
        features: ['Actes notariaux proposés', 'Prise de RDV en ligne', 'Actualités droit', 'Tarifs & honoraires', 'Zone géographique'],
        pages: ['Accueil', 'Nos actes', 'Rendez-vous', 'Actualités', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ HÔTEL ═══════════════════ */
  {
    id: 'hotel',
    icon: '🏨',
    label: 'Hôtel & Tourisme',
    color: '#EC4899',
    basePrice: 79900,
    tagline: 'Réservations directes, zéro commission',
    description: "Templates élégants pour hôtels, résidences, agences de voyage et prestataires touristiques. Augmentez vos réservations directes sans payer de commission.",
    templates: [
      {
        id: 'hotel-prestige',
        name: 'Hôtel Prestige',
        tagline: "L'hospitalité africaine d'exception",
        description: "Template grand luxe pour hôtels 4 et 5 étoiles. Chambres premium, spa, restaurant gastronomique et expérience client exclusive.",
        primaryColor: '#B45309',
        accentColor: '#FDE68A',
        bgDark: '#180800',
        style: 'luxury',
        badge: 'Bestseller',
        features: ['Galerie chambres & suites', 'Réservation directe en ligne', 'Spa & bien-être', 'Restaurant & bar', 'Services hôteliers'],
        pages: ['Accueil', 'Chambres & Suites', 'Restaurants', 'Spa', 'Événements', 'Réservation'],
      },
      {
        id: 'boutique-hotel',
        name: 'Boutique Hôtel',
        tagline: 'Petit par la taille, grand par le charme',
        description: "Template élégant pour boutique hôtels, hôtels design et maisons d'hôtes haut de gamme. Authenticité et expérience personnalisée.",
        primaryColor: '#BE185D',
        accentColor: '#FBCFE8',
        bgDark: '#1A0010',
        style: 'elegant',
        badge: 'Populaire',
        features: ['Story telling de l\'hôtel', 'Chambres thématisées', 'Expériences locales', 'Petit-déjeuner & gastronomie', 'Privatisation & événements'],
        pages: ['Accueil', 'Notre histoire', 'Chambres', 'Expériences', 'Réservation', 'Contact'],
      },
      {
        id: 'resort-tropical',
        name: 'Resort Tropical',
        tagline: 'Votre paradis en bord de mer',
        description: "Template immersif pour resorts balnéaires, clubs vacances et lodges tropicaux. Plage, piscine et activités nautiques.",
        primaryColor: '#0891B2',
        accentColor: '#67E8F9',
        bgDark: '#001018',
        style: 'bold',
        badge: 'Nouveau',
        features: ['Villas & bungalows', 'Activités nautiques & sportives', 'All inclusive packages', 'Galerie immersive', 'Réservation en ligne'],
        pages: ['Accueil', 'Hébergements', 'Activités', 'Packages', 'Galerie', 'Réservation'],
      },
      {
        id: 'residence-affaires',
        name: 'Résidence Affaires',
        tagline: 'Votre chez-vous loin de chez vous',
        description: "Template professionnel pour résidences hôtelières, appart-hôtels et hôtels business. Séjours longue durée et services pro.",
        primaryColor: '#374151',
        accentColor: '#9CA3AF',
        bgDark: '#060810',
        style: 'minimal',
        features: ['Appartements & studios', 'Services business', 'Séjours courts & longs', 'Tarifs corporate', 'Transport & navette'],
        pages: ['Accueil', 'Appartements', 'Services', 'Tarifs', 'Réservation', 'Contact'],
      },
      {
        id: 'agence-voyage',
        name: 'Agence de Voyages',
        tagline: 'Le monde à portée de votre rêve',
        description: "Template coloré pour agences de voyages, tour-opérateurs et plateformes de tourisme africain. Circuits, séjours et voyages sur mesure.",
        primaryColor: '#7C3AED',
        accentColor: '#C4B5FD',
        bgDark: '#0D001A',
        style: 'modern',
        badge: 'Populaire',
        features: ['Catalogue destinations', 'Circuits & séjours organisés', 'Devis voyage en ligne', 'Avis voyageurs', 'Réservation avec acompte'],
        pages: ['Accueil', 'Destinations', 'Circuits', 'Promotions', 'Votre voyage', 'Contact'],
      },
      {
        id: 'gite-auberge',
        name: 'Gîte & Auberge',
        tagline: 'L\'accueil authentique de nos terroirs',
        description: "Template chaleureux pour gîtes ruraux, auberges et chambres d'hôtes. Convivialité, nature et découverte locale.",
        primaryColor: '#15803D',
        accentColor: '#86EFAC',
        bgDark: '#001A08',
        style: 'warm',
        features: ['Hébergements & chambres', 'Table d\'hôtes & cuisine', 'Activités & randonnées', 'Galerie & ambiance', 'Réservation directe'],
        pages: ['Accueil', 'Hébergement', 'Table d\'hôtes', 'Activités', 'Réservation', 'Contact'],
      },
      {
        id: 'safari-lodge',
        name: 'Safari & Écotourisme',
        tagline: 'La nature africaine comme vous ne l\'avez jamais vue',
        description: "Template immersif pour lodges safari, parcs naturels et prestataires d'écotourisme. Faune, biodiversité et expériences inoubliables.",
        primaryColor: '#78350F',
        accentColor: '#FDE68A',
        bgDark: '#120600',
        style: 'natural',
        badge: 'Nouveau',
        features: ['Safaris & excursions', 'Lodges & tentes luxe', 'Galerie animaux & nature', 'Guides & équipe', 'Réservation avec calendrier'],
        pages: ['Accueil', 'Nos safaris', 'Hébergements', 'Galerie', 'Réservation', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ BEAUTÉ ═══════════════════ */
  {
    id: 'beaute',
    icon: '💄',
    label: 'Beauté & Spa',
    color: '#A855F7',
    basePrice: 49900,
    tagline: 'Sublimez votre image, développez votre clientèle',
    description: 'Templates élégants pour salons de beauté, instituts, spas et coiffeurs. Présentez vos prestations, gérez vos rendez-vous et fidélisez votre clientèle.',
    templates: [
      {
        id: 'salon-coiffure',
        name: 'Salon de Coiffure',
        tagline: 'Votre style, notre expertise',
        description: "Template moderne pour salons de coiffure et barbershops premium. Galerie coupes, équipe stylistes et RDV en ligne.",
        primaryColor: '#A21CAF',
        accentColor: '#E879F9',
        bgDark: '#150020',
        style: 'bold',
        badge: 'Bestseller',
        features: ['Catalogue prestations & prix', 'Galerie coupes & couleurs', 'RDV en ligne par coiffeur', 'Équipe stylistes', 'Produits professionnels'],
        pages: ['Accueil', 'Nos services', "L'équipe", 'Galerie', 'Rendez-vous', 'Contact'],
      },
      {
        id: 'institut-beaute',
        name: "Institut de Beauté",
        tagline: 'Révélez votre beauté naturelle',
        description: "Template luxe et féminin pour instituts de beauté complets. Soins visage, corps, épilation et massages.",
        primaryColor: '#BE185D',
        accentColor: '#FBCFE8',
        bgDark: '#1A0010',
        style: 'luxury',
        badge: 'Populaire',
        features: ['Carte soins détaillée', 'Cabines & espaces', 'RDV en ligne 24h/24', 'Produits & marques', 'Abonnements & formules'],
        pages: ['Accueil', 'Nos soins', 'Tarifs', 'Galerie', 'Rendez-vous', 'Contact'],
      },
      {
        id: 'spa-luxe',
        name: 'Spa de Luxe',
        tagline: 'Évadez-vous dans un cocon de bien-être',
        description: "Template premium pour spas haut de gamme, centres thalasso et resorts bien-être. Immersion sensorielle et sérénité.",
        primaryColor: '#0F766E',
        accentColor: '#99F6E4',
        bgDark: '#001A17',
        style: 'elegant',
        badge: 'Pro',
        features: ['Rituels & soins signature', 'Hammam & sauna', 'Packages bien-être', 'Bons cadeaux', 'Réservation en ligne'],
        pages: ['Accueil', 'Rituels', 'Packages', 'Bons cadeaux', 'Réservation', 'Contact'],
      },
      {
        id: 'barbershop',
        name: 'Barbershop',
        tagline: "L'art du rasage, la culture du style",
        description: "Template cool et masculin pour barbershops tendance. Tarifs, barbers, galerie styles et réservations.",
        primaryColor: '#1E3A5F',
        accentColor: '#93C5FD',
        bgDark: '#000A18',
        style: 'dark',
        badge: 'Populaire',
        features: ['Galerie coupes & barbes', 'Barbers & spécialités', 'Réservation en ligne', 'Produits barbier', 'Programme fidélité'],
        pages: ['Accueil', 'Services', 'Barbers', 'Galerie', 'Réservation', 'Contact'],
      },
      {
        id: 'nail-art',
        name: 'Nail Art & Ongles',
        tagline: "Des ongles parfaits, une touche de vous",
        description: "Template coloré et féminin pour nail artistes, ongleries et instituts spécialisés. Portfolio créations et RDV.",
        primaryColor: '#DB2777',
        accentColor: '#F9A8D4',
        bgDark: '#1A0010',
        style: 'modern',
        badge: 'Nouveau',
        features: ['Galerie nail art & créations', 'Prestations & durées', 'RDV en ligne', 'Galerie Instagram', 'Entretien & conseils'],
        pages: ['Accueil', 'Galerie', 'Prestations', 'Rendez-vous', 'Contact'],
      },
      {
        id: 'make-up-studio',
        name: 'Make-Up Studio',
        tagline: 'Chaque occasion, un maquillage sublime',
        description: "Template artistique pour maquilleurs professionnels, écoles de maquillage et studios beauté. Mariages, events et shooting.",
        primaryColor: '#9333EA',
        accentColor: '#D8B4FE',
        bgDark: '#110024',
        style: 'elegant',
        features: ['Portfolio mariages & events', 'Prestations à domicile', 'Cours & formations', 'Produits & techniques', 'Réservation en ligne'],
        pages: ['Accueil', 'Portfolio', 'Prestations', 'Formations', 'Réservation', 'Contact'],
      },
      {
        id: 'centre-bien-etre',
        name: 'Centre Bien-Être',
        tagline: 'Corps et esprit en harmonie',
        description: "Template apaisant pour centres de bien-être holistiques. Yoga, méditation, coaching et soins energétiques.",
        primaryColor: '#0891B2',
        accentColor: '#A5F3FC',
        bgDark: '#00101A',
        style: 'natural',
        features: ['Disciplines & pratiques', 'Planning des cours', 'Praticiens & coachs', 'Retraites & stages', 'Abonnements mensuels'],
        pages: ['Accueil', 'Disciplines', 'Planning', 'Praticiens', 'Retraites', 'Contact'],
      },
      {
        id: 'parfumerie',
        name: 'Parfumerie & Cosmétiques',
        tagline: 'L\'art du parfum, la science du soin',
        description: "Template luxe pour parfumeries, créateurs de parfums et cosmétiques artisanaux. Storytelling olfactif et boutique en ligne.",
        primaryColor: '#B45309',
        accentColor: '#FDE68A',
        bgDark: '#1A0A00',
        style: 'luxury',
        features: ['Catalogue parfums & soins', 'Univers olfactif & notes', 'Conseil personnalisé', 'Coffrets & cadeaux', 'Boutique en ligne'],
        pages: ['Accueil', 'Parfums', 'Soins', 'Coffrets', 'Notre histoire', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ AUTO ═══════════════════ */
  {
    id: 'auto',
    icon: '🚗',
    label: 'Auto & Transport',
    color: '#14B8A6',
    basePrice: 59900,
    tagline: 'Votre parc auto en ligne, clients en confiance',
    description: 'Templates dynamiques pour concessionnaires, garages, agences de location et transporteurs. Publiez votre parc, recevez des demandes et développez votre activité.',
    templates: [
      {
        id: 'concessionnaire',
        name: 'Concessionnaire Auto',
        tagline: 'Trouvez le véhicule de vos rêves',
        description: "Template dynamique pour concessionnaires automobiles et vendeurs de véhicules neufs et occasions. Catalogue, financement et essai.",
        primaryColor: '#0F766E',
        accentColor: '#5EEAD4',
        bgDark: '#001A17',
        style: 'modern',
        badge: 'Bestseller',
        features: ['Catalogue véhicules filtrable', 'Fiches techniques détaillées', 'Demande d\'essai en ligne', 'Financement & reprise', 'Comparateur de modèles'],
        pages: ['Accueil', 'Véhicules neufs', 'Occasions', 'Financement', 'Essai', 'Contact'],
      },
      {
        id: 'garage-mecanique',
        name: 'Garage Mécanique',
        tagline: 'Votre voiture entre de bonnes mains',
        description: "Template professionnel pour garages mécaniques, centres auto et ateliers de réparation. Services, devis et prise de RDV.",
        primaryColor: '#374151',
        accentColor: '#9CA3AF',
        bgDark: '#060810',
        style: 'bold',
        badge: 'Populaire',
        features: ['Services mécaniques proposés', 'Prise de RDV atelier', 'Devis en ligne', 'Pièces & accessoires', 'Suivi dossier réparation'],
        pages: ['Accueil', 'Nos services', 'Rendez-vous', 'Devis', 'Boutique', 'Contact'],
      },
      {
        id: 'location-vehicules',
        name: 'Location de Véhicules',
        tagline: 'La liberté de la route, sans contrainte',
        description: "Template clair pour agences de location courte et longue durée. Catalogue, disponibilités et réservation sécurisée.",
        primaryColor: '#0284C7',
        accentColor: '#7DD3FC',
        bgDark: '#000D1A',
        style: 'classic',
        badge: 'Nouveau',
        features: ['Catalogue véhicules disponibles', 'Réservation avec dates', 'Tarifs journaliers & forfaits', 'Livraison & reprise', 'Assurances incluses'],
        pages: ['Accueil', 'Nos véhicules', 'Tarifs', 'Réservation', 'Conditions', 'Contact'],
      },
      {
        id: 'transport-taxi',
        name: 'Transport & Taxi',
        tagline: 'À l\'heure, à chaque fois',
        description: "Template pratique pour compagnies de transport, VTC et services de taxi premium. Réservation et traçabilité.",
        primaryColor: '#D97706',
        accentColor: '#FCD34D',
        bgDark: '#1A0F00',
        style: 'dark',
        features: ['Services & trajets proposés', 'Devis et réservation en ligne', 'Flotte & véhicules', 'Fidélité entreprises', 'Application mobile ready'],
        pages: ['Accueil', 'Nos services', 'Réservation', 'Flotte', 'Entreprises', 'Contact'],
      },
      {
        id: 'pieces-auto',
        name: 'Pièces & Accessoires Auto',
        tagline: 'Toutes les pièces, livrées vite',
        description: "Template e-commerce pour distributeurs de pièces automobiles et accessoires. Catalogue, compatibilité véhicule et livraison.",
        primaryColor: '#DC2626',
        accentColor: '#FCA5A5',
        bgDark: '#1A0000',
        style: 'bold',
        badge: 'Pro',
        features: ['Catalogue pièces multi-marques', 'Recherche par modèle & année', 'Devis et commande', 'Livraison express', 'SAV & retours'],
        pages: ['Accueil', 'Catalogue', 'Recherche par véhicule', 'Promotions', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ AGRICULTURE ═══════════════════ */
  {
    id: 'agriculture',
    icon: '🌾',
    label: 'Agriculture',
    color: '#84CC16',
    basePrice: 49900,
    tagline: 'Connectez vos produits aux marchés',
    description: "Templates professionnels pour agriculteurs, coopératives, agro-industries et fournisseurs d'intrants. Présentez vos produits et développez vos débouchés commerciaux.",
    templates: [
      {
        id: 'ferme-bio',
        name: 'Ferme Biologique',
        tagline: "Du champ à votre assiette, en toute transparence",
        description: "Template naturel et transparent pour fermes bio, producteurs locaux et circuits courts. Traçabilité produits et vente directe.",
        primaryColor: '#15803D',
        accentColor: '#86EFAC',
        bgDark: '#001A08',
        style: 'natural',
        badge: 'Bestseller',
        features: ['Catalogue produits bio', 'Traçabilité & certification', 'Panier hebdomadaire', 'Blog & recettes', 'Vente directe & livraison'],
        pages: ['Accueil', 'Nos produits', 'Notre ferme', 'Panier bio', 'Blog', 'Contact'],
      },
      {
        id: 'cooperative',
        name: 'Coopérative Agricole',
        tagline: "Ensemble, plus forts sur les marchés",
        description: "Template institutionnel pour coopératives agricoles et groupements de producteurs. Gouvernance, production et commercialisation.",
        primaryColor: '#65A30D',
        accentColor: '#BEF264',
        bgDark: '#061A00',
        style: 'classic',
        badge: 'Populaire',
        features: ['Présentation coopérative', 'Catalogue produits membres', 'Adhésion en ligne', 'Rapports & gouvernance', 'Acheteurs & partenaires'],
        pages: ['Accueil', 'Nos produits', 'Adhérer', 'Gouvernance', 'Actualités', 'Contact'],
      },
      {
        id: 'agro-industrie',
        name: 'Agro-Industrie',
        tagline: 'Transformer pour valoriser',
        description: "Template professionnel pour unités de transformation, agro-industries et exportateurs de produits agricoles transformés.",
        primaryColor: '#D97706',
        accentColor: '#FCD34D',
        bgDark: '#1A0F00',
        style: 'modern',
        badge: 'Pro',
        features: ['Gamme de produits transformés', 'Capacités de production', 'Certifications export', 'Partenaires & distributeurs', 'Demande de commande B2B'],
        pages: ['Accueil', 'Nos produits', 'Production', 'Export', 'Partenaires', 'Contact'],
      },
      {
        id: 'pepiniere',
        name: 'Pépinière & Plantes',
        tagline: "La nature commence ici",
        description: "Template coloré et vivant pour pépinières, jardineries et fournisseurs de plants. Catalogue en ligne et conseil cultivation.",
        primaryColor: '#16A34A',
        accentColor: '#86EFAC',
        bgDark: '#001A08',
        style: 'natural',
        badge: 'Nouveau',
        features: ['Catalogue plants & arbres', 'Conseils culture & entretien', 'Commande en ligne', 'Livraison & transport plants', 'Blog jardinage tropical'],
        pages: ['Accueil', 'Nos plants', 'Conseils', 'Commander', 'Blog', 'Contact'],
      },
    ],
  },

  /* ═══════════════════ CORPORATE ═══════════════════ */
  {
    id: 'corporate',
    icon: '💼',
    label: 'Corporate & Finance',
    color: '#64748B',
    basePrice: 69900,
    tagline: "L'image de marque qui inspire confiance",
    description: "Templates haut de gamme pour grandes entreprises, banques, assurances et institutions financières. Communiquez votre vision et attirez partenaires et investisseurs.",
    templates: [
      {
        id: 'holding-finance',
        name: 'Holding & Finance',
        tagline: 'Vision stratégique, impact durable',
        description: "Template sobre et puissant pour holdings, groupes d'investissement et conglomérats. Portefeuille, gouvernance et résultats.",
        primaryColor: '#1E3A5F',
        accentColor: '#93C5FD',
        bgDark: '#000A18',
        style: 'dark',
        badge: 'Pro',
        features: ['Portefeuille filiales & participations', 'Rapport annuel digital', 'Équipe dirigeante', 'Actualités corporate', 'Espace investisseurs'],
        pages: ['Accueil', 'Notre groupe', 'Activités', 'Gouvernance', 'Investisseurs', 'Contact'],
      },
      {
        id: 'banque-microfinance',
        name: 'Banque & Microfinance',
        tagline: 'Financer vos projets, accélérer votre croissance',
        description: "Template crédible pour banques, institutions de microfinance et coopératives d'épargne. Produits, simulation et agences.",
        primaryColor: '#1D4ED8',
        accentColor: '#BFDBFE',
        bgDark: '#00061A',
        style: 'classic',
        badge: 'Bestseller',
        features: ['Produits bancaires & épargne', 'Simulateur crédit en ligne', 'Réseau agences', 'Actualités financières', 'Espace client bancaire'],
        pages: ['Accueil', 'Nos produits', 'Simulateur', 'Agences', 'Actualités', 'Contact'],
      },
      {
        id: 'assurance',
        name: "Compagnie d'Assurance",
        tagline: 'Protéger ce qui compte pour vous',
        description: "Template rassurant pour compagnies d'assurance vie, auto, santé et habitation. Devis en ligne et réseau courtiers.",
        primaryColor: '#0F766E',
        accentColor: '#5EEAD4',
        bgDark: '#001A17',
        style: 'minimal',
        badge: 'Pro',
        features: ['Gamme de produits assurance', 'Devis en ligne instantané', 'Réseau agents & courtiers', 'Sinistres en ligne', 'FAQ & guides'],
        pages: ['Accueil', 'Nos assurances', 'Devis', 'Agents', 'Sinistres', 'Contact'],
      },
      {
        id: 'audit-conseil',
        name: 'Audit & Conseil',
        tagline: "Votre performance, notre engagement",
        description: "Template élégant pour cabinets d'audit, sociétés de conseil en stratégie et management consultants internationaux.",
        primaryColor: '#374151',
        accentColor: '#D1D5DB',
        bgDark: '#060810',
        style: 'luxury',
        features: ['Services audit & assurance', 'Conseil stratégique & RH', 'Secteurs d\'intervention', 'Études de cas', 'Leadership & équipe'],
        pages: ['Accueil', 'Nos services', 'Secteurs', 'Insights', 'Équipe', 'Contact'],
      },
      {
        id: 'startup-tech',
        name: 'Startup Tech',
        tagline: "Disrupting the future, today",
        description: "Template moderne pour startups, scale-ups et entreprises technologiques africaines. Produit, équipe, investisseurs.",
        primaryColor: '#7C3AED',
        accentColor: '#C4B5FD',
        bgDark: '#0D001A',
        style: 'dark',
        badge: 'Populaire',
        features: ['Produit & fonctionnalités', 'Pitch deck digital', 'Équipe & culture', 'Levées de fonds', 'Blog tech & actualités'],
        pages: ['Accueil', 'Produit', 'Équipe', 'Investors', 'Blog', 'Contact'],
      },
      {
        id: 'ong-association',
        name: 'ONG & Association',
        tagline: 'Agir ensemble pour un monde meilleur',
        description: "Template engagé pour ONG, associations humanitaires et fondations. Mission, impact, projets et collecte de dons.",
        primaryColor: '#16A34A',
        accentColor: '#86EFAC',
        bgDark: '#001A08',
        style: 'warm',
        badge: 'Nouveau',
        features: ['Mission & vision', 'Projets & impact terrain', 'Collecte de dons en ligne', 'Rapports & transparence', 'Bénévolat & adhésion'],
        pages: ['Accueil', 'Notre mission', 'Projets', 'Faire un don', 'Rapports', 'Contact'],
      },
      {
        id: 'media-presse',
        name: 'Média & Presse',
        tagline: "L'information africaine, en temps réel",
        description: "Template dynamique pour journaux en ligne, médias digitaux et portails d'information africains. Articles, podcasts et vidéos.",
        primaryColor: '#DC2626',
        accentColor: '#FCA5A5',
        bgDark: '#1A0000',
        style: 'bold',
        badge: 'Populaire',
        features: ['Articles & catégories', 'Podcast & vidéos intégrés', 'Newsletter & abonnés', 'Réseaux sociaux live', 'Espace publicité'],
        pages: ['Accueil', 'Actualités', 'Politique', 'Économie', 'Culture', 'Contact'],
      },
      {
        id: 'institution-pub',
        name: 'Institution Publique',
        tagline: "Servir les citoyens avec transparence",
        description: "Template sobre et officiel pour mairies, ministères, collectivités et institutions publiques africaines. Services citoyens en ligne.",
        primaryColor: '#1D4ED8',
        accentColor: '#BFDBFE',
        bgDark: '#00061A',
        style: 'classic',
        features: ['Services administratifs en ligne', 'Actualités & communiqués', 'Élus & direction', 'Documents & formulaires', 'Contact & réclamations'],
        pages: ['Accueil', 'Services', 'Actualités', 'Élus', 'Documents', 'Contact'],
      },
      {
        id: 'industrie',
        name: 'Industrie & Manufacturing',
        tagline: "Produire local, vendre global",
        description: "Template puissant pour industriels, fabricants et exportateurs africains. Capacités, produits et partenariats B2B.",
        primaryColor: '#78350F',
        accentColor: '#FDE68A',
        bgDark: '#120600',
        style: 'dark',
        badge: 'Pro',
        features: ['Gamme de produits industriels', 'Capacités de production', 'Certifications & normes', 'Partenaires & distribution', 'Demande B2B en ligne'],
        pages: ['Accueil', 'Produits', 'Production', 'Certifications', 'Partenaires', 'Contact'],
      },
    ],
  },
]

export const SECTORS_MAP = Object.fromEntries(SECTORS_DATA.map((s) => [s.id, s]))
